// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// NewCreateHTTPStorageParams creates a new CreateHTTPStorageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateHTTPStorageParams() *CreateHTTPStorageParams {
	return &CreateHTTPStorageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateHTTPStorageParamsWithTimeout creates a new CreateHTTPStorageParams object
// with the ability to set a timeout on a request.
func NewCreateHTTPStorageParamsWithTimeout(timeout time.Duration) *CreateHTTPStorageParams {
	return &CreateHTTPStorageParams{
		timeout: timeout,
	}
}

// NewCreateHTTPStorageParamsWithContext creates a new CreateHTTPStorageParams object
// with the ability to set a context for a request.
func NewCreateHTTPStorageParamsWithContext(ctx context.Context) *CreateHTTPStorageParams {
	return &CreateHTTPStorageParams{
		Context: ctx,
	}
}

// NewCreateHTTPStorageParamsWithHTTPClient creates a new CreateHTTPStorageParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateHTTPStorageParamsWithHTTPClient(client *http.Client) *CreateHTTPStorageParams {
	return &CreateHTTPStorageParams{
		HTTPClient: client,
	}
}

/*
CreateHTTPStorageParams contains all the parameters to send to the API endpoint

	for the create Http storage operation.

	Typically these are written to a http.Request.
*/
type CreateHTTPStorageParams struct {

	/* Request.

	   Request body
	*/
	Request *models.StorageCreateHTTPStorageRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create Http storage params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateHTTPStorageParams) WithDefaults() *CreateHTTPStorageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create Http storage params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateHTTPStorageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create Http storage params
func (o *CreateHTTPStorageParams) WithTimeout(timeout time.Duration) *CreateHTTPStorageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create Http storage params
func (o *CreateHTTPStorageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create Http storage params
func (o *CreateHTTPStorageParams) WithContext(ctx context.Context) *CreateHTTPStorageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create Http storage params
func (o *CreateHTTPStorageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create Http storage params
func (o *CreateHTTPStorageParams) WithHTTPClient(client *http.Client) *CreateHTTPStorageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create Http storage params
func (o *CreateHTTPStorageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the create Http storage params
func (o *CreateHTTPStorageParams) WithRequest(request *models.StorageCreateHTTPStorageRequest) *CreateHTTPStorageParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the create Http storage params
func (o *CreateHTTPStorageParams) SetRequest(request *models.StorageCreateHTTPStorageRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *CreateHTTPStorageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
