// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// CreateStorageReader is a Reader for the CreateStorage structure.
type CreateStorageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateStorageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateStorageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateStorageBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateStorageInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /storage/{storageType}] CreateStorage", response, response.Code())
	}
}

// NewCreateStorageOK creates a CreateStorageOK with default headers values
func NewCreateStorageOK() *CreateStorageOK {
	return &CreateStorageOK{}
}

/*
CreateStorageOK describes a response with status code 200, with default header values.

OK
*/
type CreateStorageOK struct {
	Payload *models.ModelStorage
}

// IsSuccess returns true when this create storage o k response has a 2xx status code
func (o *CreateStorageOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create storage o k response has a 3xx status code
func (o *CreateStorageOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create storage o k response has a 4xx status code
func (o *CreateStorageOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create storage o k response has a 5xx status code
func (o *CreateStorageOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create storage o k response a status code equal to that given
func (o *CreateStorageOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create storage o k response
func (o *CreateStorageOK) Code() int {
	return 200
}

func (o *CreateStorageOK) Error() string {
	return fmt.Sprintf("[POST /storage/{storageType}][%d] createStorageOK  %+v", 200, o.Payload)
}

func (o *CreateStorageOK) String() string {
	return fmt.Sprintf("[POST /storage/{storageType}][%d] createStorageOK  %+v", 200, o.Payload)
}

func (o *CreateStorageOK) GetPayload() *models.ModelStorage {
	return o.Payload
}

func (o *CreateStorageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelStorage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateStorageBadRequest creates a CreateStorageBadRequest with default headers values
func NewCreateStorageBadRequest() *CreateStorageBadRequest {
	return &CreateStorageBadRequest{}
}

/*
CreateStorageBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateStorageBadRequest struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this create storage bad request response has a 2xx status code
func (o *CreateStorageBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create storage bad request response has a 3xx status code
func (o *CreateStorageBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create storage bad request response has a 4xx status code
func (o *CreateStorageBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create storage bad request response has a 5xx status code
func (o *CreateStorageBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create storage bad request response a status code equal to that given
func (o *CreateStorageBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create storage bad request response
func (o *CreateStorageBadRequest) Code() int {
	return 400
}

func (o *CreateStorageBadRequest) Error() string {
	return fmt.Sprintf("[POST /storage/{storageType}][%d] createStorageBadRequest  %+v", 400, o.Payload)
}

func (o *CreateStorageBadRequest) String() string {
	return fmt.Sprintf("[POST /storage/{storageType}][%d] createStorageBadRequest  %+v", 400, o.Payload)
}

func (o *CreateStorageBadRequest) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *CreateStorageBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateStorageInternalServerError creates a CreateStorageInternalServerError with default headers values
func NewCreateStorageInternalServerError() *CreateStorageInternalServerError {
	return &CreateStorageInternalServerError{}
}

/*
CreateStorageInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateStorageInternalServerError struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this create storage internal server error response has a 2xx status code
func (o *CreateStorageInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create storage internal server error response has a 3xx status code
func (o *CreateStorageInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create storage internal server error response has a 4xx status code
func (o *CreateStorageInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create storage internal server error response has a 5xx status code
func (o *CreateStorageInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create storage internal server error response a status code equal to that given
func (o *CreateStorageInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create storage internal server error response
func (o *CreateStorageInternalServerError) Code() int {
	return 500
}

func (o *CreateStorageInternalServerError) Error() string {
	return fmt.Sprintf("[POST /storage/{storageType}][%d] createStorageInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateStorageInternalServerError) String() string {
	return fmt.Sprintf("[POST /storage/{storageType}][%d] createStorageInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateStorageInternalServerError) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *CreateStorageInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
