// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// NewCreateAcdStorageParams creates a new CreateAcdStorageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateAcdStorageParams() *CreateAcdStorageParams {
	return &CreateAcdStorageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateAcdStorageParamsWithTimeout creates a new CreateAcdStorageParams object
// with the ability to set a timeout on a request.
func NewCreateAcdStorageParamsWithTimeout(timeout time.Duration) *CreateAcdStorageParams {
	return &CreateAcdStorageParams{
		timeout: timeout,
	}
}

// NewCreateAcdStorageParamsWithContext creates a new CreateAcdStorageParams object
// with the ability to set a context for a request.
func NewCreateAcdStorageParamsWithContext(ctx context.Context) *CreateAcdStorageParams {
	return &CreateAcdStorageParams{
		Context: ctx,
	}
}

// NewCreateAcdStorageParamsWithHTTPClient creates a new CreateAcdStorageParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateAcdStorageParamsWithHTTPClient(client *http.Client) *CreateAcdStorageParams {
	return &CreateAcdStorageParams{
		HTTPClient: client,
	}
}

/*
CreateAcdStorageParams contains all the parameters to send to the API endpoint

	for the create acd storage operation.

	Typically these are written to a http.Request.
*/
type CreateAcdStorageParams struct {

	/* Request.

	   Request body
	*/
	Request *models.StorageCreateAcdStorageRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create acd storage params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateAcdStorageParams) WithDefaults() *CreateAcdStorageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create acd storage params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateAcdStorageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create acd storage params
func (o *CreateAcdStorageParams) WithTimeout(timeout time.Duration) *CreateAcdStorageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create acd storage params
func (o *CreateAcdStorageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create acd storage params
func (o *CreateAcdStorageParams) WithContext(ctx context.Context) *CreateAcdStorageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create acd storage params
func (o *CreateAcdStorageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create acd storage params
func (o *CreateAcdStorageParams) WithHTTPClient(client *http.Client) *CreateAcdStorageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create acd storage params
func (o *CreateAcdStorageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the create acd storage params
func (o *CreateAcdStorageParams) WithRequest(request *models.StorageCreateAcdStorageRequest) *CreateAcdStorageParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the create acd storage params
func (o *CreateAcdStorageParams) SetRequest(request *models.StorageCreateAcdStorageRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *CreateAcdStorageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
