// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// CreateS3CubbitStorageReader is a Reader for the CreateS3CubbitStorage structure.
type CreateS3CubbitStorageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateS3CubbitStorageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewCreateS3CubbitStorageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateS3CubbitStorageBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateS3CubbitStorageInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /storage/s3/cubbit] CreateS3CubbitStorage", response, response.Code())
	}
}

// NewCreateS3CubbitStorageOK creates a CreateS3CubbitStorageOK with default headers values
func NewCreateS3CubbitStorageOK() *CreateS3CubbitStorageOK {
	return &CreateS3CubbitStorageOK{}
}

/*
CreateS3CubbitStorageOK describes a response with status code 200, with default header values.

OK
*/
type CreateS3CubbitStorageOK struct {
	Payload *models.ModelStorage
}

// IsSuccess returns true when this create s3 cubbit storage o k response has a 2xx status code
func (o *CreateS3CubbitStorageOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create s3 cubbit storage o k response has a 3xx status code
func (o *CreateS3CubbitStorageOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create s3 cubbit storage o k response has a 4xx status code
func (o *CreateS3CubbitStorageOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create s3 cubbit storage o k response has a 5xx status code
func (o *CreateS3CubbitStorageOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create s3 cubbit storage o k response a status code equal to that given
func (o *CreateS3CubbitStorageOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create s3 cubbit storage o k response
func (o *CreateS3CubbitStorageOK) Code() int {
	return 200
}

func (o *CreateS3CubbitStorageOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /storage/s3/cubbit][%d] createS3CubbitStorageOK %s", 200, payload)
}

func (o *CreateS3CubbitStorageOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /storage/s3/cubbit][%d] createS3CubbitStorageOK %s", 200, payload)
}

func (o *CreateS3CubbitStorageOK) GetPayload() *models.ModelStorage {
	return o.Payload
}

func (o *CreateS3CubbitStorageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelStorage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateS3CubbitStorageBadRequest creates a CreateS3CubbitStorageBadRequest with default headers values
func NewCreateS3CubbitStorageBadRequest() *CreateS3CubbitStorageBadRequest {
	return &CreateS3CubbitStorageBadRequest{}
}

/*
CreateS3CubbitStorageBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateS3CubbitStorageBadRequest struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this create s3 cubbit storage bad request response has a 2xx status code
func (o *CreateS3CubbitStorageBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create s3 cubbit storage bad request response has a 3xx status code
func (o *CreateS3CubbitStorageBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create s3 cubbit storage bad request response has a 4xx status code
func (o *CreateS3CubbitStorageBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create s3 cubbit storage bad request response has a 5xx status code
func (o *CreateS3CubbitStorageBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create s3 cubbit storage bad request response a status code equal to that given
func (o *CreateS3CubbitStorageBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create s3 cubbit storage bad request response
func (o *CreateS3CubbitStorageBadRequest) Code() int {
	return 400
}

func (o *CreateS3CubbitStorageBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /storage/s3/cubbit][%d] createS3CubbitStorageBadRequest %s", 400, payload)
}

func (o *CreateS3CubbitStorageBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /storage/s3/cubbit][%d] createS3CubbitStorageBadRequest %s", 400, payload)
}

func (o *CreateS3CubbitStorageBadRequest) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *CreateS3CubbitStorageBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateS3CubbitStorageInternalServerError creates a CreateS3CubbitStorageInternalServerError with default headers values
func NewCreateS3CubbitStorageInternalServerError() *CreateS3CubbitStorageInternalServerError {
	return &CreateS3CubbitStorageInternalServerError{}
}

/*
CreateS3CubbitStorageInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateS3CubbitStorageInternalServerError struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this create s3 cubbit storage internal server error response has a 2xx status code
func (o *CreateS3CubbitStorageInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create s3 cubbit storage internal server error response has a 3xx status code
func (o *CreateS3CubbitStorageInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create s3 cubbit storage internal server error response has a 4xx status code
func (o *CreateS3CubbitStorageInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create s3 cubbit storage internal server error response has a 5xx status code
func (o *CreateS3CubbitStorageInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create s3 cubbit storage internal server error response a status code equal to that given
func (o *CreateS3CubbitStorageInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create s3 cubbit storage internal server error response
func (o *CreateS3CubbitStorageInternalServerError) Code() int {
	return 500
}

func (o *CreateS3CubbitStorageInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /storage/s3/cubbit][%d] createS3CubbitStorageInternalServerError %s", 500, payload)
}

func (o *CreateS3CubbitStorageInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /storage/s3/cubbit][%d] createS3CubbitStorageInternalServerError %s", 500, payload)
}

func (o *CreateS3CubbitStorageInternalServerError) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *CreateS3CubbitStorageInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
