// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// CreateFilefabricStorageReader is a Reader for the CreateFilefabricStorage structure.
type CreateFilefabricStorageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateFilefabricStorageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateFilefabricStorageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateFilefabricStorageBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateFilefabricStorageInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /storage/filefabric] CreateFilefabricStorage", response, response.Code())
	}
}

// NewCreateFilefabricStorageOK creates a CreateFilefabricStorageOK with default headers values
func NewCreateFilefabricStorageOK() *CreateFilefabricStorageOK {
	return &CreateFilefabricStorageOK{}
}

/*
CreateFilefabricStorageOK describes a response with status code 200, with default header values.

OK
*/
type CreateFilefabricStorageOK struct {
	Payload *models.ModelStorage
}

// IsSuccess returns true when this create filefabric storage o k response has a 2xx status code
func (o *CreateFilefabricStorageOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create filefabric storage o k response has a 3xx status code
func (o *CreateFilefabricStorageOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create filefabric storage o k response has a 4xx status code
func (o *CreateFilefabricStorageOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create filefabric storage o k response has a 5xx status code
func (o *CreateFilefabricStorageOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create filefabric storage o k response a status code equal to that given
func (o *CreateFilefabricStorageOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create filefabric storage o k response
func (o *CreateFilefabricStorageOK) Code() int {
	return 200
}

func (o *CreateFilefabricStorageOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /storage/filefabric][%d] createFilefabricStorageOK %s", 200, payload)
}

func (o *CreateFilefabricStorageOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /storage/filefabric][%d] createFilefabricStorageOK %s", 200, payload)
}

func (o *CreateFilefabricStorageOK) GetPayload() *models.ModelStorage {
	return o.Payload
}

func (o *CreateFilefabricStorageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelStorage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateFilefabricStorageBadRequest creates a CreateFilefabricStorageBadRequest with default headers values
func NewCreateFilefabricStorageBadRequest() *CreateFilefabricStorageBadRequest {
	return &CreateFilefabricStorageBadRequest{}
}

/*
CreateFilefabricStorageBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateFilefabricStorageBadRequest struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this create filefabric storage bad request response has a 2xx status code
func (o *CreateFilefabricStorageBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create filefabric storage bad request response has a 3xx status code
func (o *CreateFilefabricStorageBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create filefabric storage bad request response has a 4xx status code
func (o *CreateFilefabricStorageBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create filefabric storage bad request response has a 5xx status code
func (o *CreateFilefabricStorageBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create filefabric storage bad request response a status code equal to that given
func (o *CreateFilefabricStorageBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create filefabric storage bad request response
func (o *CreateFilefabricStorageBadRequest) Code() int {
	return 400
}

func (o *CreateFilefabricStorageBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /storage/filefabric][%d] createFilefabricStorageBadRequest %s", 400, payload)
}

func (o *CreateFilefabricStorageBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /storage/filefabric][%d] createFilefabricStorageBadRequest %s", 400, payload)
}

func (o *CreateFilefabricStorageBadRequest) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *CreateFilefabricStorageBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateFilefabricStorageInternalServerError creates a CreateFilefabricStorageInternalServerError with default headers values
func NewCreateFilefabricStorageInternalServerError() *CreateFilefabricStorageInternalServerError {
	return &CreateFilefabricStorageInternalServerError{}
}

/*
CreateFilefabricStorageInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateFilefabricStorageInternalServerError struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this create filefabric storage internal server error response has a 2xx status code
func (o *CreateFilefabricStorageInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create filefabric storage internal server error response has a 3xx status code
func (o *CreateFilefabricStorageInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create filefabric storage internal server error response has a 4xx status code
func (o *CreateFilefabricStorageInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create filefabric storage internal server error response has a 5xx status code
func (o *CreateFilefabricStorageInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create filefabric storage internal server error response a status code equal to that given
func (o *CreateFilefabricStorageInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create filefabric storage internal server error response
func (o *CreateFilefabricStorageInternalServerError) Code() int {
	return 500
}

func (o *CreateFilefabricStorageInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /storage/filefabric][%d] createFilefabricStorageInternalServerError %s", 500, payload)
}

func (o *CreateFilefabricStorageInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /storage/filefabric][%d] createFilefabricStorageInternalServerError %s", 500, payload)
}

func (o *CreateFilefabricStorageInternalServerError) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *CreateFilefabricStorageInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
