// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// CreateDropboxStorageReader is a Reader for the CreateDropboxStorage structure.
type CreateDropboxStorageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateDropboxStorageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateDropboxStorageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateDropboxStorageBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateDropboxStorageInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /storage/dropbox] CreateDropboxStorage", response, response.Code())
	}
}

// NewCreateDropboxStorageOK creates a CreateDropboxStorageOK with default headers values
func NewCreateDropboxStorageOK() *CreateDropboxStorageOK {
	return &CreateDropboxStorageOK{}
}

/*
CreateDropboxStorageOK describes a response with status code 200, with default header values.

OK
*/
type CreateDropboxStorageOK struct {
	Payload *models.ModelStorage
}

// IsSuccess returns true when this create dropbox storage o k response has a 2xx status code
func (o *CreateDropboxStorageOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create dropbox storage o k response has a 3xx status code
func (o *CreateDropboxStorageOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create dropbox storage o k response has a 4xx status code
func (o *CreateDropboxStorageOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create dropbox storage o k response has a 5xx status code
func (o *CreateDropboxStorageOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create dropbox storage o k response a status code equal to that given
func (o *CreateDropboxStorageOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create dropbox storage o k response
func (o *CreateDropboxStorageOK) Code() int {
	return 200
}

func (o *CreateDropboxStorageOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /storage/dropbox][%d] createDropboxStorageOK %s", 200, payload)
}

func (o *CreateDropboxStorageOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /storage/dropbox][%d] createDropboxStorageOK %s", 200, payload)
}

func (o *CreateDropboxStorageOK) GetPayload() *models.ModelStorage {
	return o.Payload
}

func (o *CreateDropboxStorageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelStorage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateDropboxStorageBadRequest creates a CreateDropboxStorageBadRequest with default headers values
func NewCreateDropboxStorageBadRequest() *CreateDropboxStorageBadRequest {
	return &CreateDropboxStorageBadRequest{}
}

/*
CreateDropboxStorageBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateDropboxStorageBadRequest struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this create dropbox storage bad request response has a 2xx status code
func (o *CreateDropboxStorageBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create dropbox storage bad request response has a 3xx status code
func (o *CreateDropboxStorageBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create dropbox storage bad request response has a 4xx status code
func (o *CreateDropboxStorageBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create dropbox storage bad request response has a 5xx status code
func (o *CreateDropboxStorageBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create dropbox storage bad request response a status code equal to that given
func (o *CreateDropboxStorageBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create dropbox storage bad request response
func (o *CreateDropboxStorageBadRequest) Code() int {
	return 400
}

func (o *CreateDropboxStorageBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /storage/dropbox][%d] createDropboxStorageBadRequest %s", 400, payload)
}

func (o *CreateDropboxStorageBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /storage/dropbox][%d] createDropboxStorageBadRequest %s", 400, payload)
}

func (o *CreateDropboxStorageBadRequest) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *CreateDropboxStorageBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateDropboxStorageInternalServerError creates a CreateDropboxStorageInternalServerError with default headers values
func NewCreateDropboxStorageInternalServerError() *CreateDropboxStorageInternalServerError {
	return &CreateDropboxStorageInternalServerError{}
}

/*
CreateDropboxStorageInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateDropboxStorageInternalServerError struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this create dropbox storage internal server error response has a 2xx status code
func (o *CreateDropboxStorageInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create dropbox storage internal server error response has a 3xx status code
func (o *CreateDropboxStorageInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create dropbox storage internal server error response has a 4xx status code
func (o *CreateDropboxStorageInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create dropbox storage internal server error response has a 5xx status code
func (o *CreateDropboxStorageInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create dropbox storage internal server error response a status code equal to that given
func (o *CreateDropboxStorageInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create dropbox storage internal server error response
func (o *CreateDropboxStorageInternalServerError) Code() int {
	return 500
}

func (o *CreateDropboxStorageInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /storage/dropbox][%d] createDropboxStorageInternalServerError %s", 500, payload)
}

func (o *CreateDropboxStorageInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /storage/dropbox][%d] createDropboxStorageInternalServerError %s", 500, payload)
}

func (o *CreateDropboxStorageInternalServerError) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *CreateDropboxStorageInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
