// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// CreateS3AlibabaStorageReader is a Reader for the CreateS3AlibabaStorage structure.
type CreateS3AlibabaStorageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateS3AlibabaStorageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateS3AlibabaStorageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateS3AlibabaStorageBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateS3AlibabaStorageInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /storage/s3/alibaba] CreateS3AlibabaStorage", response, response.Code())
	}
}

// NewCreateS3AlibabaStorageOK creates a CreateS3AlibabaStorageOK with default headers values
func NewCreateS3AlibabaStorageOK() *CreateS3AlibabaStorageOK {
	return &CreateS3AlibabaStorageOK{}
}

/*
CreateS3AlibabaStorageOK describes a response with status code 200, with default header values.

OK
*/
type CreateS3AlibabaStorageOK struct {
	Payload *models.ModelStorage
}

// IsSuccess returns true when this create s3 alibaba storage o k response has a 2xx status code
func (o *CreateS3AlibabaStorageOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create s3 alibaba storage o k response has a 3xx status code
func (o *CreateS3AlibabaStorageOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create s3 alibaba storage o k response has a 4xx status code
func (o *CreateS3AlibabaStorageOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create s3 alibaba storage o k response has a 5xx status code
func (o *CreateS3AlibabaStorageOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create s3 alibaba storage o k response a status code equal to that given
func (o *CreateS3AlibabaStorageOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create s3 alibaba storage o k response
func (o *CreateS3AlibabaStorageOK) Code() int {
	return 200
}

func (o *CreateS3AlibabaStorageOK) Error() string {
	return fmt.Sprintf("[POST /storage/s3/alibaba][%d] createS3AlibabaStorageOK  %+v", 200, o.Payload)
}

func (o *CreateS3AlibabaStorageOK) String() string {
	return fmt.Sprintf("[POST /storage/s3/alibaba][%d] createS3AlibabaStorageOK  %+v", 200, o.Payload)
}

func (o *CreateS3AlibabaStorageOK) GetPayload() *models.ModelStorage {
	return o.Payload
}

func (o *CreateS3AlibabaStorageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelStorage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateS3AlibabaStorageBadRequest creates a CreateS3AlibabaStorageBadRequest with default headers values
func NewCreateS3AlibabaStorageBadRequest() *CreateS3AlibabaStorageBadRequest {
	return &CreateS3AlibabaStorageBadRequest{}
}

/*
CreateS3AlibabaStorageBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateS3AlibabaStorageBadRequest struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this create s3 alibaba storage bad request response has a 2xx status code
func (o *CreateS3AlibabaStorageBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create s3 alibaba storage bad request response has a 3xx status code
func (o *CreateS3AlibabaStorageBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create s3 alibaba storage bad request response has a 4xx status code
func (o *CreateS3AlibabaStorageBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create s3 alibaba storage bad request response has a 5xx status code
func (o *CreateS3AlibabaStorageBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create s3 alibaba storage bad request response a status code equal to that given
func (o *CreateS3AlibabaStorageBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create s3 alibaba storage bad request response
func (o *CreateS3AlibabaStorageBadRequest) Code() int {
	return 400
}

func (o *CreateS3AlibabaStorageBadRequest) Error() string {
	return fmt.Sprintf("[POST /storage/s3/alibaba][%d] createS3AlibabaStorageBadRequest  %+v", 400, o.Payload)
}

func (o *CreateS3AlibabaStorageBadRequest) String() string {
	return fmt.Sprintf("[POST /storage/s3/alibaba][%d] createS3AlibabaStorageBadRequest  %+v", 400, o.Payload)
}

func (o *CreateS3AlibabaStorageBadRequest) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *CreateS3AlibabaStorageBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateS3AlibabaStorageInternalServerError creates a CreateS3AlibabaStorageInternalServerError with default headers values
func NewCreateS3AlibabaStorageInternalServerError() *CreateS3AlibabaStorageInternalServerError {
	return &CreateS3AlibabaStorageInternalServerError{}
}

/*
CreateS3AlibabaStorageInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateS3AlibabaStorageInternalServerError struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this create s3 alibaba storage internal server error response has a 2xx status code
func (o *CreateS3AlibabaStorageInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create s3 alibaba storage internal server error response has a 3xx status code
func (o *CreateS3AlibabaStorageInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create s3 alibaba storage internal server error response has a 4xx status code
func (o *CreateS3AlibabaStorageInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create s3 alibaba storage internal server error response has a 5xx status code
func (o *CreateS3AlibabaStorageInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create s3 alibaba storage internal server error response a status code equal to that given
func (o *CreateS3AlibabaStorageInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create s3 alibaba storage internal server error response
func (o *CreateS3AlibabaStorageInternalServerError) Code() int {
	return 500
}

func (o *CreateS3AlibabaStorageInternalServerError) Error() string {
	return fmt.Sprintf("[POST /storage/s3/alibaba][%d] createS3AlibabaStorageInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateS3AlibabaStorageInternalServerError) String() string {
	return fmt.Sprintf("[POST /storage/s3/alibaba][%d] createS3AlibabaStorageInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateS3AlibabaStorageInternalServerError) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *CreateS3AlibabaStorageInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
