// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// NewCreateMegaStorageParams creates a new CreateMegaStorageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateMegaStorageParams() *CreateMegaStorageParams {
	return &CreateMegaStorageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateMegaStorageParamsWithTimeout creates a new CreateMegaStorageParams object
// with the ability to set a timeout on a request.
func NewCreateMegaStorageParamsWithTimeout(timeout time.Duration) *CreateMegaStorageParams {
	return &CreateMegaStorageParams{
		timeout: timeout,
	}
}

// NewCreateMegaStorageParamsWithContext creates a new CreateMegaStorageParams object
// with the ability to set a context for a request.
func NewCreateMegaStorageParamsWithContext(ctx context.Context) *CreateMegaStorageParams {
	return &CreateMegaStorageParams{
		Context: ctx,
	}
}

// NewCreateMegaStorageParamsWithHTTPClient creates a new CreateMegaStorageParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateMegaStorageParamsWithHTTPClient(client *http.Client) *CreateMegaStorageParams {
	return &CreateMegaStorageParams{
		HTTPClient: client,
	}
}

/*
CreateMegaStorageParams contains all the parameters to send to the API endpoint

	for the create mega storage operation.

	Typically these are written to a http.Request.
*/
type CreateMegaStorageParams struct {

	/* Request.

	   Request body
	*/
	Request *models.StorageCreateMegaStorageRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create mega storage params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateMegaStorageParams) WithDefaults() *CreateMegaStorageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create mega storage params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateMegaStorageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create mega storage params
func (o *CreateMegaStorageParams) WithTimeout(timeout time.Duration) *CreateMegaStorageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create mega storage params
func (o *CreateMegaStorageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create mega storage params
func (o *CreateMegaStorageParams) WithContext(ctx context.Context) *CreateMegaStorageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create mega storage params
func (o *CreateMegaStorageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create mega storage params
func (o *CreateMegaStorageParams) WithHTTPClient(client *http.Client) *CreateMegaStorageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create mega storage params
func (o *CreateMegaStorageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the create mega storage params
func (o *CreateMegaStorageParams) WithRequest(request *models.StorageCreateMegaStorageRequest) *CreateMegaStorageParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the create mega storage params
func (o *CreateMegaStorageParams) SetRequest(request *models.StorageCreateMegaStorageRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *CreateMegaStorageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
