// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// NewPostStorageBoxParams creates a new PostStorageBoxParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostStorageBoxParams() *PostStorageBoxParams {
	return &PostStorageBoxParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostStorageBoxParamsWithTimeout creates a new PostStorageBoxParams object
// with the ability to set a timeout on a request.
func NewPostStorageBoxParamsWithTimeout(timeout time.Duration) *PostStorageBoxParams {
	return &PostStorageBoxParams{
		timeout: timeout,
	}
}

// NewPostStorageBoxParamsWithContext creates a new PostStorageBoxParams object
// with the ability to set a context for a request.
func NewPostStorageBoxParamsWithContext(ctx context.Context) *PostStorageBoxParams {
	return &PostStorageBoxParams{
		Context: ctx,
	}
}

// NewPostStorageBoxParamsWithHTTPClient creates a new PostStorageBoxParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostStorageBoxParamsWithHTTPClient(client *http.Client) *PostStorageBoxParams {
	return &PostStorageBoxParams{
		HTTPClient: client,
	}
}

/*
PostStorageBoxParams contains all the parameters to send to the API endpoint

	for the post storage box operation.

	Typically these are written to a http.Request.
*/
type PostStorageBoxParams struct {

	/* Request.

	   Request body
	*/
	Request *models.StorageCreateBoxStorageRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post storage box params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostStorageBoxParams) WithDefaults() *PostStorageBoxParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post storage box params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostStorageBoxParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post storage box params
func (o *PostStorageBoxParams) WithTimeout(timeout time.Duration) *PostStorageBoxParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post storage box params
func (o *PostStorageBoxParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post storage box params
func (o *PostStorageBoxParams) WithContext(ctx context.Context) *PostStorageBoxParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post storage box params
func (o *PostStorageBoxParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post storage box params
func (o *PostStorageBoxParams) WithHTTPClient(client *http.Client) *PostStorageBoxParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post storage box params
func (o *PostStorageBoxParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post storage box params
func (o *PostStorageBoxParams) WithRequest(request *models.StorageCreateBoxStorageRequest) *PostStorageBoxParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post storage box params
func (o *PostStorageBoxParams) SetRequest(request *models.StorageCreateBoxStorageRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostStorageBoxParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
