// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// NewPostStorageS3RackcorpParams creates a new PostStorageS3RackcorpParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostStorageS3RackcorpParams() *PostStorageS3RackcorpParams {
	return &PostStorageS3RackcorpParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostStorageS3RackcorpParamsWithTimeout creates a new PostStorageS3RackcorpParams object
// with the ability to set a timeout on a request.
func NewPostStorageS3RackcorpParamsWithTimeout(timeout time.Duration) *PostStorageS3RackcorpParams {
	return &PostStorageS3RackcorpParams{
		timeout: timeout,
	}
}

// NewPostStorageS3RackcorpParamsWithContext creates a new PostStorageS3RackcorpParams object
// with the ability to set a context for a request.
func NewPostStorageS3RackcorpParamsWithContext(ctx context.Context) *PostStorageS3RackcorpParams {
	return &PostStorageS3RackcorpParams{
		Context: ctx,
	}
}

// NewPostStorageS3RackcorpParamsWithHTTPClient creates a new PostStorageS3RackcorpParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostStorageS3RackcorpParamsWithHTTPClient(client *http.Client) *PostStorageS3RackcorpParams {
	return &PostStorageS3RackcorpParams{
		HTTPClient: client,
	}
}

/*
PostStorageS3RackcorpParams contains all the parameters to send to the API endpoint

	for the post storage s3 rackcorp operation.

	Typically these are written to a http.Request.
*/
type PostStorageS3RackcorpParams struct {

	/* Request.

	   Request body
	*/
	Request *models.StorageCreateS3RackCorpStorageRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post storage s3 rackcorp params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostStorageS3RackcorpParams) WithDefaults() *PostStorageS3RackcorpParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post storage s3 rackcorp params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostStorageS3RackcorpParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post storage s3 rackcorp params
func (o *PostStorageS3RackcorpParams) WithTimeout(timeout time.Duration) *PostStorageS3RackcorpParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post storage s3 rackcorp params
func (o *PostStorageS3RackcorpParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post storage s3 rackcorp params
func (o *PostStorageS3RackcorpParams) WithContext(ctx context.Context) *PostStorageS3RackcorpParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post storage s3 rackcorp params
func (o *PostStorageS3RackcorpParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post storage s3 rackcorp params
func (o *PostStorageS3RackcorpParams) WithHTTPClient(client *http.Client) *PostStorageS3RackcorpParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post storage s3 rackcorp params
func (o *PostStorageS3RackcorpParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post storage s3 rackcorp params
func (o *PostStorageS3RackcorpParams) WithRequest(request *models.StorageCreateS3RackCorpStorageRequest) *PostStorageS3RackcorpParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post storage s3 rackcorp params
func (o *PostStorageS3RackcorpParams) SetRequest(request *models.StorageCreateS3RackCorpStorageRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostStorageS3RackcorpParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
