// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// NewPostStorageS3ChinamobileParams creates a new PostStorageS3ChinamobileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostStorageS3ChinamobileParams() *PostStorageS3ChinamobileParams {
	return &PostStorageS3ChinamobileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostStorageS3ChinamobileParamsWithTimeout creates a new PostStorageS3ChinamobileParams object
// with the ability to set a timeout on a request.
func NewPostStorageS3ChinamobileParamsWithTimeout(timeout time.Duration) *PostStorageS3ChinamobileParams {
	return &PostStorageS3ChinamobileParams{
		timeout: timeout,
	}
}

// NewPostStorageS3ChinamobileParamsWithContext creates a new PostStorageS3ChinamobileParams object
// with the ability to set a context for a request.
func NewPostStorageS3ChinamobileParamsWithContext(ctx context.Context) *PostStorageS3ChinamobileParams {
	return &PostStorageS3ChinamobileParams{
		Context: ctx,
	}
}

// NewPostStorageS3ChinamobileParamsWithHTTPClient creates a new PostStorageS3ChinamobileParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostStorageS3ChinamobileParamsWithHTTPClient(client *http.Client) *PostStorageS3ChinamobileParams {
	return &PostStorageS3ChinamobileParams{
		HTTPClient: client,
	}
}

/*
PostStorageS3ChinamobileParams contains all the parameters to send to the API endpoint

	for the post storage s3 chinamobile operation.

	Typically these are written to a http.Request.
*/
type PostStorageS3ChinamobileParams struct {

	/* Request.

	   Request body
	*/
	Request *models.StorageCreateS3ChinaMobileStorageRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post storage s3 chinamobile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostStorageS3ChinamobileParams) WithDefaults() *PostStorageS3ChinamobileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post storage s3 chinamobile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostStorageS3ChinamobileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post storage s3 chinamobile params
func (o *PostStorageS3ChinamobileParams) WithTimeout(timeout time.Duration) *PostStorageS3ChinamobileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post storage s3 chinamobile params
func (o *PostStorageS3ChinamobileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post storage s3 chinamobile params
func (o *PostStorageS3ChinamobileParams) WithContext(ctx context.Context) *PostStorageS3ChinamobileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post storage s3 chinamobile params
func (o *PostStorageS3ChinamobileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post storage s3 chinamobile params
func (o *PostStorageS3ChinamobileParams) WithHTTPClient(client *http.Client) *PostStorageS3ChinamobileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post storage s3 chinamobile params
func (o *PostStorageS3ChinamobileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post storage s3 chinamobile params
func (o *PostStorageS3ChinamobileParams) WithRequest(request *models.StorageCreateS3ChinaMobileStorageRequest) *PostStorageS3ChinamobileParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post storage s3 chinamobile params
func (o *PostStorageS3ChinamobileParams) SetRequest(request *models.StorageCreateS3ChinaMobileStorageRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostStorageS3ChinamobileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
