// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// PostStorageS3LiaraReader is a Reader for the PostStorageS3Liara structure.
type PostStorageS3LiaraReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostStorageS3LiaraReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostStorageS3LiaraOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostStorageS3LiaraBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostStorageS3LiaraInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /storage/s3/liara] PostStorageS3Liara", response, response.Code())
	}
}

// NewPostStorageS3LiaraOK creates a PostStorageS3LiaraOK with default headers values
func NewPostStorageS3LiaraOK() *PostStorageS3LiaraOK {
	return &PostStorageS3LiaraOK{}
}

/*
PostStorageS3LiaraOK describes a response with status code 200, with default header values.

OK
*/
type PostStorageS3LiaraOK struct {
	Payload *models.ModelStorage
}

// IsSuccess returns true when this post storage s3 liara o k response has a 2xx status code
func (o *PostStorageS3LiaraOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post storage s3 liara o k response has a 3xx status code
func (o *PostStorageS3LiaraOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post storage s3 liara o k response has a 4xx status code
func (o *PostStorageS3LiaraOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post storage s3 liara o k response has a 5xx status code
func (o *PostStorageS3LiaraOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post storage s3 liara o k response a status code equal to that given
func (o *PostStorageS3LiaraOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post storage s3 liara o k response
func (o *PostStorageS3LiaraOK) Code() int {
	return 200
}

func (o *PostStorageS3LiaraOK) Error() string {
	return fmt.Sprintf("[POST /storage/s3/liara][%d] postStorageS3LiaraOK  %+v", 200, o.Payload)
}

func (o *PostStorageS3LiaraOK) String() string {
	return fmt.Sprintf("[POST /storage/s3/liara][%d] postStorageS3LiaraOK  %+v", 200, o.Payload)
}

func (o *PostStorageS3LiaraOK) GetPayload() *models.ModelStorage {
	return o.Payload
}

func (o *PostStorageS3LiaraOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelStorage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostStorageS3LiaraBadRequest creates a PostStorageS3LiaraBadRequest with default headers values
func NewPostStorageS3LiaraBadRequest() *PostStorageS3LiaraBadRequest {
	return &PostStorageS3LiaraBadRequest{}
}

/*
PostStorageS3LiaraBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostStorageS3LiaraBadRequest struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this post storage s3 liara bad request response has a 2xx status code
func (o *PostStorageS3LiaraBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post storage s3 liara bad request response has a 3xx status code
func (o *PostStorageS3LiaraBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post storage s3 liara bad request response has a 4xx status code
func (o *PostStorageS3LiaraBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post storage s3 liara bad request response has a 5xx status code
func (o *PostStorageS3LiaraBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post storage s3 liara bad request response a status code equal to that given
func (o *PostStorageS3LiaraBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post storage s3 liara bad request response
func (o *PostStorageS3LiaraBadRequest) Code() int {
	return 400
}

func (o *PostStorageS3LiaraBadRequest) Error() string {
	return fmt.Sprintf("[POST /storage/s3/liara][%d] postStorageS3LiaraBadRequest  %+v", 400, o.Payload)
}

func (o *PostStorageS3LiaraBadRequest) String() string {
	return fmt.Sprintf("[POST /storage/s3/liara][%d] postStorageS3LiaraBadRequest  %+v", 400, o.Payload)
}

func (o *PostStorageS3LiaraBadRequest) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *PostStorageS3LiaraBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostStorageS3LiaraInternalServerError creates a PostStorageS3LiaraInternalServerError with default headers values
func NewPostStorageS3LiaraInternalServerError() *PostStorageS3LiaraInternalServerError {
	return &PostStorageS3LiaraInternalServerError{}
}

/*
PostStorageS3LiaraInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostStorageS3LiaraInternalServerError struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this post storage s3 liara internal server error response has a 2xx status code
func (o *PostStorageS3LiaraInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post storage s3 liara internal server error response has a 3xx status code
func (o *PostStorageS3LiaraInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post storage s3 liara internal server error response has a 4xx status code
func (o *PostStorageS3LiaraInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post storage s3 liara internal server error response has a 5xx status code
func (o *PostStorageS3LiaraInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post storage s3 liara internal server error response a status code equal to that given
func (o *PostStorageS3LiaraInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post storage s3 liara internal server error response
func (o *PostStorageS3LiaraInternalServerError) Code() int {
	return 500
}

func (o *PostStorageS3LiaraInternalServerError) Error() string {
	return fmt.Sprintf("[POST /storage/s3/liara][%d] postStorageS3LiaraInternalServerError  %+v", 500, o.Payload)
}

func (o *PostStorageS3LiaraInternalServerError) String() string {
	return fmt.Sprintf("[POST /storage/s3/liara][%d] postStorageS3LiaraInternalServerError  %+v", 500, o.Payload)
}

func (o *PostStorageS3LiaraInternalServerError) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *PostStorageS3LiaraInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
