// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// PostStorageStorjNewReader is a Reader for the PostStorageStorjNew structure.
type PostStorageStorjNewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostStorageStorjNewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostStorageStorjNewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostStorageStorjNewBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostStorageStorjNewInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /storage/storj/new] PostStorageStorjNew", response, response.Code())
	}
}

// NewPostStorageStorjNewOK creates a PostStorageStorjNewOK with default headers values
func NewPostStorageStorjNewOK() *PostStorageStorjNewOK {
	return &PostStorageStorjNewOK{}
}

/*
PostStorageStorjNewOK describes a response with status code 200, with default header values.

OK
*/
type PostStorageStorjNewOK struct {
	Payload *models.ModelStorage
}

// IsSuccess returns true when this post storage storj new o k response has a 2xx status code
func (o *PostStorageStorjNewOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post storage storj new o k response has a 3xx status code
func (o *PostStorageStorjNewOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post storage storj new o k response has a 4xx status code
func (o *PostStorageStorjNewOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post storage storj new o k response has a 5xx status code
func (o *PostStorageStorjNewOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post storage storj new o k response a status code equal to that given
func (o *PostStorageStorjNewOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post storage storj new o k response
func (o *PostStorageStorjNewOK) Code() int {
	return 200
}

func (o *PostStorageStorjNewOK) Error() string {
	return fmt.Sprintf("[POST /storage/storj/new][%d] postStorageStorjNewOK  %+v", 200, o.Payload)
}

func (o *PostStorageStorjNewOK) String() string {
	return fmt.Sprintf("[POST /storage/storj/new][%d] postStorageStorjNewOK  %+v", 200, o.Payload)
}

func (o *PostStorageStorjNewOK) GetPayload() *models.ModelStorage {
	return o.Payload
}

func (o *PostStorageStorjNewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelStorage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostStorageStorjNewBadRequest creates a PostStorageStorjNewBadRequest with default headers values
func NewPostStorageStorjNewBadRequest() *PostStorageStorjNewBadRequest {
	return &PostStorageStorjNewBadRequest{}
}

/*
PostStorageStorjNewBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostStorageStorjNewBadRequest struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this post storage storj new bad request response has a 2xx status code
func (o *PostStorageStorjNewBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post storage storj new bad request response has a 3xx status code
func (o *PostStorageStorjNewBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post storage storj new bad request response has a 4xx status code
func (o *PostStorageStorjNewBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post storage storj new bad request response has a 5xx status code
func (o *PostStorageStorjNewBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post storage storj new bad request response a status code equal to that given
func (o *PostStorageStorjNewBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post storage storj new bad request response
func (o *PostStorageStorjNewBadRequest) Code() int {
	return 400
}

func (o *PostStorageStorjNewBadRequest) Error() string {
	return fmt.Sprintf("[POST /storage/storj/new][%d] postStorageStorjNewBadRequest  %+v", 400, o.Payload)
}

func (o *PostStorageStorjNewBadRequest) String() string {
	return fmt.Sprintf("[POST /storage/storj/new][%d] postStorageStorjNewBadRequest  %+v", 400, o.Payload)
}

func (o *PostStorageStorjNewBadRequest) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *PostStorageStorjNewBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostStorageStorjNewInternalServerError creates a PostStorageStorjNewInternalServerError with default headers values
func NewPostStorageStorjNewInternalServerError() *PostStorageStorjNewInternalServerError {
	return &PostStorageStorjNewInternalServerError{}
}

/*
PostStorageStorjNewInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostStorageStorjNewInternalServerError struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this post storage storj new internal server error response has a 2xx status code
func (o *PostStorageStorjNewInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post storage storj new internal server error response has a 3xx status code
func (o *PostStorageStorjNewInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post storage storj new internal server error response has a 4xx status code
func (o *PostStorageStorjNewInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post storage storj new internal server error response has a 5xx status code
func (o *PostStorageStorjNewInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post storage storj new internal server error response a status code equal to that given
func (o *PostStorageStorjNewInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post storage storj new internal server error response
func (o *PostStorageStorjNewInternalServerError) Code() int {
	return 500
}

func (o *PostStorageStorjNewInternalServerError) Error() string {
	return fmt.Sprintf("[POST /storage/storj/new][%d] postStorageStorjNewInternalServerError  %+v", 500, o.Payload)
}

func (o *PostStorageStorjNewInternalServerError) String() string {
	return fmt.Sprintf("[POST /storage/storj/new][%d] postStorageStorjNewInternalServerError  %+v", 500, o.Payload)
}

func (o *PostStorageStorjNewInternalServerError) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *PostStorageStorjNewInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
