// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// PostStorageSwiftReader is a Reader for the PostStorageSwift structure.
type PostStorageSwiftReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostStorageSwiftReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostStorageSwiftOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostStorageSwiftBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostStorageSwiftInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /storage/swift] PostStorageSwift", response, response.Code())
	}
}

// NewPostStorageSwiftOK creates a PostStorageSwiftOK with default headers values
func NewPostStorageSwiftOK() *PostStorageSwiftOK {
	return &PostStorageSwiftOK{}
}

/*
PostStorageSwiftOK describes a response with status code 200, with default header values.

OK
*/
type PostStorageSwiftOK struct {
	Payload *models.ModelStorage
}

// IsSuccess returns true when this post storage swift o k response has a 2xx status code
func (o *PostStorageSwiftOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post storage swift o k response has a 3xx status code
func (o *PostStorageSwiftOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post storage swift o k response has a 4xx status code
func (o *PostStorageSwiftOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post storage swift o k response has a 5xx status code
func (o *PostStorageSwiftOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post storage swift o k response a status code equal to that given
func (o *PostStorageSwiftOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post storage swift o k response
func (o *PostStorageSwiftOK) Code() int {
	return 200
}

func (o *PostStorageSwiftOK) Error() string {
	return fmt.Sprintf("[POST /storage/swift][%d] postStorageSwiftOK  %+v", 200, o.Payload)
}

func (o *PostStorageSwiftOK) String() string {
	return fmt.Sprintf("[POST /storage/swift][%d] postStorageSwiftOK  %+v", 200, o.Payload)
}

func (o *PostStorageSwiftOK) GetPayload() *models.ModelStorage {
	return o.Payload
}

func (o *PostStorageSwiftOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelStorage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostStorageSwiftBadRequest creates a PostStorageSwiftBadRequest with default headers values
func NewPostStorageSwiftBadRequest() *PostStorageSwiftBadRequest {
	return &PostStorageSwiftBadRequest{}
}

/*
PostStorageSwiftBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostStorageSwiftBadRequest struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this post storage swift bad request response has a 2xx status code
func (o *PostStorageSwiftBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post storage swift bad request response has a 3xx status code
func (o *PostStorageSwiftBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post storage swift bad request response has a 4xx status code
func (o *PostStorageSwiftBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post storage swift bad request response has a 5xx status code
func (o *PostStorageSwiftBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post storage swift bad request response a status code equal to that given
func (o *PostStorageSwiftBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post storage swift bad request response
func (o *PostStorageSwiftBadRequest) Code() int {
	return 400
}

func (o *PostStorageSwiftBadRequest) Error() string {
	return fmt.Sprintf("[POST /storage/swift][%d] postStorageSwiftBadRequest  %+v", 400, o.Payload)
}

func (o *PostStorageSwiftBadRequest) String() string {
	return fmt.Sprintf("[POST /storage/swift][%d] postStorageSwiftBadRequest  %+v", 400, o.Payload)
}

func (o *PostStorageSwiftBadRequest) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *PostStorageSwiftBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostStorageSwiftInternalServerError creates a PostStorageSwiftInternalServerError with default headers values
func NewPostStorageSwiftInternalServerError() *PostStorageSwiftInternalServerError {
	return &PostStorageSwiftInternalServerError{}
}

/*
PostStorageSwiftInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostStorageSwiftInternalServerError struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this post storage swift internal server error response has a 2xx status code
func (o *PostStorageSwiftInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post storage swift internal server error response has a 3xx status code
func (o *PostStorageSwiftInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post storage swift internal server error response has a 4xx status code
func (o *PostStorageSwiftInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post storage swift internal server error response has a 5xx status code
func (o *PostStorageSwiftInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post storage swift internal server error response a status code equal to that given
func (o *PostStorageSwiftInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post storage swift internal server error response
func (o *PostStorageSwiftInternalServerError) Code() int {
	return 500
}

func (o *PostStorageSwiftInternalServerError) Error() string {
	return fmt.Sprintf("[POST /storage/swift][%d] postStorageSwiftInternalServerError  %+v", 500, o.Payload)
}

func (o *PostStorageSwiftInternalServerError) String() string {
	return fmt.Sprintf("[POST /storage/swift][%d] postStorageSwiftInternalServerError  %+v", 500, o.Payload)
}

func (o *PostStorageSwiftInternalServerError) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *PostStorageSwiftInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
