// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// NewPostStorageFichierParams creates a new PostStorageFichierParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostStorageFichierParams() *PostStorageFichierParams {
	return &PostStorageFichierParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostStorageFichierParamsWithTimeout creates a new PostStorageFichierParams object
// with the ability to set a timeout on a request.
func NewPostStorageFichierParamsWithTimeout(timeout time.Duration) *PostStorageFichierParams {
	return &PostStorageFichierParams{
		timeout: timeout,
	}
}

// NewPostStorageFichierParamsWithContext creates a new PostStorageFichierParams object
// with the ability to set a context for a request.
func NewPostStorageFichierParamsWithContext(ctx context.Context) *PostStorageFichierParams {
	return &PostStorageFichierParams{
		Context: ctx,
	}
}

// NewPostStorageFichierParamsWithHTTPClient creates a new PostStorageFichierParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostStorageFichierParamsWithHTTPClient(client *http.Client) *PostStorageFichierParams {
	return &PostStorageFichierParams{
		HTTPClient: client,
	}
}

/*
PostStorageFichierParams contains all the parameters to send to the API endpoint

	for the post storage fichier operation.

	Typically these are written to a http.Request.
*/
type PostStorageFichierParams struct {

	/* Request.

	   Request body
	*/
	Request *models.StorageCreateFichierStorageRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post storage fichier params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostStorageFichierParams) WithDefaults() *PostStorageFichierParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post storage fichier params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostStorageFichierParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post storage fichier params
func (o *PostStorageFichierParams) WithTimeout(timeout time.Duration) *PostStorageFichierParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post storage fichier params
func (o *PostStorageFichierParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post storage fichier params
func (o *PostStorageFichierParams) WithContext(ctx context.Context) *PostStorageFichierParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post storage fichier params
func (o *PostStorageFichierParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post storage fichier params
func (o *PostStorageFichierParams) WithHTTPClient(client *http.Client) *PostStorageFichierParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post storage fichier params
func (o *PostStorageFichierParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post storage fichier params
func (o *PostStorageFichierParams) WithRequest(request *models.StorageCreateFichierStorageRequest) *PostStorageFichierParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post storage fichier params
func (o *PostStorageFichierParams) SetRequest(request *models.StorageCreateFichierStorageRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostStorageFichierParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
