version: v1
run:
  tests: false
linters:
  enable-all: true
  disable:
    - containedctx
    - cyclop
    - depguard
    - dupl
    - dupword
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox
    - gomoddirectives
    - interfacebloat
    - ireturn
    - lll
    - maintidx
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilnil
    - nlreturn
    - nolintlint
    - nonamedreturns
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
    - contextcheck
    - forcetypeassert
    - exhaustive
    - intrange
    - staticcheck
    - errchkjson
    - exportloopref
linters-settings:
    gosec:
      excludes:
        - G115 # we do a lot of uint64 conversions unfortunately
    errcheck:
      exclude-functions:
        - path/filepath.Walk
        - (github.com/libp2p/go-libp2p/network.MuxedStream).SetDeadline
        - (github.com/data-preservation-programs/singularity/service.DatasetWorker).cleanup
    revive:
      rules:
        - name: var-naming
          disabled: true
issues:
  exclude-generated: lax
  exclude-dirs:
    - third_party
    - builtin
    - examples
  exclude-rules:
    - path: model/basetypes.go
      linters:
        - recvcheck
    - path: migrate/migrations/
      linters:
        - stylecheck
