version: "2"
run:
  tests: false
  skip-dirs:
    - replication/internal
    - cmd/embed
    - docs
    - dashboard/model2ts
    - handler/datasource/generate
    - handler/storage/gen
  skip-files:
    - cmd/testutil.go

linters:
  enable-all: true
  disable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - cyclop
    - depguard
    - dogsled
    - dupl
    - dupword
    - errname
    - errorlint
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - tparallel
    - unconvert
    - unparam
    - unused
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl

formatters:
  disable:
    - gci
    - gofumpt
    - goimports

linters-settings:
  errcheck:
    exclude-functions:
      - (github.com/libp2p/go-libp2p/network.MuxedStream).SetDeadline
      - (github.com/data-preservation-programs/singularity/service.DatasetWorker).cleanup
  revive:
    rules:
      - name: var-naming
        disabled: true
