version: "3.8"

services:
  mysql-test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: singularity
      MYSQL_USER: singularity
      MYSQL_PASSWORD: singularity
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "singularity", "-psingularity"]
      interval: 10s
      timeout: 5s
      retries: 5
    tmpfs:
      - /var/lib/mysql:exec,size=1G

  postgres-test:
    image: postgres:15
    environment:
      POSTGRES_DB: singularity
      POSTGRES_USER: singularity
      POSTGRES_PASSWORD: singularity
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U singularity -d singularity"]
      interval: 10s
      timeout: 5s
      retries: 5
    tmpfs:
      - /var/lib/postgresql/data:exec,size=1G