// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DatasourceCreatePackJobRequest datasource create pack job request
//
// swagger:model datasource.CreatePackJobRequest
type DatasourceCreatePackJobRequest struct {

	// file i ds
	FileIDs []int64 `json:"fileIDs"`
}

// Validate validates this datasource create pack job request
func (m *DatasourceCreatePackJobRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this datasource create pack job request based on context it is used
func (m *DatasourceCreatePackJobRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DatasourceCreatePackJobRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DatasourceCreatePackJobRequest) UnmarshalBinary(b []byte) error {
	var res DatasourceCreatePackJobRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
