// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DataprepDeletePieceRequest dataprep delete piece request
//
// swagger:model dataprep.DeletePieceRequest
type DataprepDeletePieceRequest struct {

	// Delete the physical CAR file from storage (default: true)
	DeleteCar bool `json:"deleteCar,omitempty"`

	// Delete even if deals reference this piece
	Force bool `json:"force,omitempty"`
}

// Validate validates this dataprep delete piece request
func (m *DataprepDeletePieceRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dataprep delete piece request based on context it is used
func (m *DataprepDeletePieceRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DataprepDeletePieceRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DataprepDeletePieceRequest) UnmarshalBinary(b []byte) error {
	var res DataprepDeletePieceRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
