// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DatasourceFileInfo datasource file info
//
// swagger:model datasource.FileInfo
type DatasourceFileInfo struct {

	// Path to the new file, relative to the source
	Path string `json:"path,omitempty"`
}

// Validate validates this datasource file info
func (m *DatasourceFileInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this datasource file info based on context it is used
func (m *DatasourceFileInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DatasourceFileInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DatasourceFileInfo) UnmarshalBinary(b []byte) error {
	var res DatasourceFileInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
