// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelFileRange model file range
//
// swagger:model model.FileRange
type ModelFileRange struct {

	// CID is the CID of the range.
	Cid string `json:"cid,omitempty"`

	// file Id
	FileID int64 `json:"fileId,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// Associations
	JobID int64 `json:"jobId,omitempty"`

	// Length is the length of the range in bytes.
	Length int64 `json:"length,omitempty"`

	// Offset is the offset of the range inside the file.
	Offset int64 `json:"offset,omitempty"`
}

// Validate validates this model file range
func (m *ModelFileRange) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model file range based on context it is used
func (m *ModelFileRange) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelFileRange) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelFileRange) UnmarshalBinary(b []byte) error {
	var res ModelFileRange
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
