// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ModelDealType model deal type
//
// swagger:model model.DealType
type ModelDealType string

func NewModelDealType(value ModelDealType) *ModelDealType {
	return &value
}

// Pointer returns a pointer to a freshly-allocated ModelDealType.
func (m ModelDealType) Pointer() *ModelDealType {
	return &m
}

const (

	// ModelDealTypeMarket captures enum value "market"
	ModelDealTypeMarket ModelDealType = "market"

	// ModelDealTypePdp captures enum value "pdp"
	ModelDealTypePdp ModelDealType = "pdp"
)

// for schema
var modelDealTypeEnum []any

func init() {
	var res []ModelDealType
	if err := json.Unmarshal([]byte(`["market","pdp"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		modelDealTypeEnum = append(modelDealTypeEnum, v)
	}
}

func (m ModelDealType) validateModelDealTypeEnum(path, location string, value ModelDealType) error {
	if err := validate.EnumCase(path, location, value, modelDealTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this model deal type
func (m ModelDealType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateModelDealTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this model deal type based on context it is used
func (m ModelDealType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
