// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ModelConfigMap model config map
//
// swagger:model model.ConfigMap
type ModelConfigMap map[string]string

// Validate validates this model config map
func (m ModelConfigMap) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model config map based on context it is used
func (m ModelConfigMap) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
