// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SppoolCreateRequest sppool create request
//
// swagger:model sppool.CreateRequest
type SppoolCreateRequest struct {

	// duration
	Duration *string `json:"duration,omitempty"`

	// force
	Force bool `json:"force,omitempty"`

	// http headers to be passed with the request (i.e. key=value)
	HTTPHeaders []string `json:"httpHeaders"`

	// ipni
	Ipni *bool `json:"ipni,omitempty"`

	// keep unsealed
	KeepUnsealed *bool `json:"keepUnsealed,omitempty"`

	// max pending deal number
	MaxPendingDealNumber int64 `json:"maxPendingDealNumber,omitempty"`

	// max pending deal size
	MaxPendingDealSize string `json:"maxPendingDealSize,omitempty"`

	// Pool name (must be unique)
	Name string `json:"name,omitempty"`

	// Notes
	Notes string `json:"notes,omitempty"`

	// price per deal
	PricePerDeal float64 `json:"pricePerDeal,omitempty"`

	// price per gb
	PricePerGb float64 `json:"pricePerGb,omitempty"`

	// price per gb epoch
	PricePerGbEpoch float64 `json:"pricePerGbEpoch,omitempty"`

	// schedule cron
	ScheduleCron string `json:"scheduleCron,omitempty"`

	// schedule cron perpetual
	ScheduleCronPerpetual bool `json:"scheduleCronPerpetual,omitempty"`

	// schedule deal number
	ScheduleDealNumber int64 `json:"scheduleDealNumber,omitempty"`

	// schedule deal size
	ScheduleDealSize string `json:"scheduleDealSize,omitempty"`

	// start delay
	StartDelay *string `json:"startDelay,omitempty"`

	// URL template with PIECE_CID placeholder
	URLTemplate string `json:"urlTemplate,omitempty"`

	// verified
	Verified *bool `json:"verified,omitempty"`
}

// Validate validates this sppool create request
func (m *SppoolCreateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sppool create request based on context it is used
func (m *SppoolCreateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SppoolCreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SppoolCreateRequest) UnmarshalBinary(b []byte) error {
	var res SppoolCreateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
