// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StoragePremiumizemeConfig storage premiumizeme config
//
// swagger:model storage.premiumizemeConfig
type StoragePremiumizemeConfig struct {

	// API Key.
	APIKey string `json:"apiKey,omitempty"`

	// Auth server URL.
	AuthURL string `json:"authUrl,omitempty"`

	// OAuth Client Id.
	ClientID string `json:"clientId,omitempty"`

	// OAuth Client Secret.
	ClientSecret string `json:"clientSecret,omitempty"`

	// Description of the remote.
	Description string `json:"description,omitempty"`

	// The encoding for the backend.
	Encoding *string `json:"encoding,omitempty"`

	// OAuth Access Token as a JSON blob.
	Token string `json:"token,omitempty"`

	// Token server url.
	TokenURL string `json:"tokenUrl,omitempty"`
}

// Validate validates this storage premiumizeme config
func (m *StoragePremiumizemeConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this storage premiumizeme config based on context it is used
func (m *StoragePremiumizemeConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StoragePremiumizemeConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StoragePremiumizemeConfig) UnmarshalBinary(b []byte) error {
	var res StoragePremiumizemeConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
