// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// StorageCreateInternetarchiveStorageRequest storage create internetarchive storage request
//
// swagger:model storage.CreateInternetarchiveStorageRequest
type StorageCreateInternetarchiveStorageRequest interface{}
