// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StorageSiaConfig storage sia config
//
// swagger:model storage.siaConfig
type StorageSiaConfig struct {

	// Sia Daemon API Password.
	APIPassword string `json:"apiPassword,omitempty"`

	// Sia daemon API URL, like http://sia.daemon.host:9980.
	APIURL *string `json:"apiUrl,omitempty"`

	// Description of the remote.
	Description string `json:"description,omitempty"`

	// The encoding for the backend.
	Encoding *string `json:"encoding,omitempty"`

	// Siad User Agent
	UserAgent *string `json:"userAgent,omitempty"`
}

// Validate validates this storage sia config
func (m *StorageSiaConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this storage sia config based on context it is used
func (m *StorageSiaConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StorageSiaConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StorageSiaConfig) UnmarshalBinary(b []byte) error {
	var res StorageSiaConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
