// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// StorageCreateS3MinioStorageRequest storage create s3 minio storage request
//
// swagger:model storage.CreateS3MinioStorageRequest
type StorageCreateS3MinioStorageRequest interface{}
