// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StoragePutioConfig storage putio config
//
// swagger:model storage.putioConfig
type StoragePutioConfig struct {

	// The encoding for the backend.
	Encoding *string `json:"encoding,omitempty"`
}

// Validate validates this storage putio config
func (m *StoragePutioConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this storage putio config based on context it is used
func (m *StoragePutioConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StoragePutioConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StoragePutioConfig) UnmarshalBinary(b []byte) error {
	var res StoragePutioConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
