// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// StorageCreateS3IBMCOSStorageRequest storage create s3 i b m c o s storage request
//
// swagger:model storage.CreateS3IBMCOSStorageRequest
type StorageCreateS3IBMCOSStorageRequest interface{}
