// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WalletCreateRequest wallet create request
//
// swagger:model wallet.CreateRequest
type WalletCreateRequest struct {

	// This is either "secp256k1" or "bls"
	KeyType string `json:"keyType,omitempty"`
}

// Validate validates this wallet create request
func (m *WalletCreateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this wallet create request based on context it is used
func (m *WalletCreateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WalletCreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WalletCreateRequest) UnmarshalBinary(b []byte) error {
	var res WalletCreateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
