// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WalletUpdateRequest wallet update request
//
// swagger:model wallet.UpdateRequest
type WalletUpdateRequest struct {

	// Name is readable label for the wallet
	ActorName string `json:"actorName,omitempty"`

	// Contact is optional email for SP wallets
	ContactInfo string `json:"contactInfo,omitempty"`

	// Location is optional region, country for SP wallets
	Location string `json:"location,omitempty"`
}

// Validate validates this wallet update request
func (m *WalletUpdateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this wallet update request based on context it is used
func (m *WalletUpdateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WalletUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WalletUpdateRequest) UnmarshalBinary(b []byte) error {
	var res WalletUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
