// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WalletImportRequest wallet import request
//
// swagger:model wallet.ImportRequest
type WalletImportRequest struct {

	// Optional contact information
	Contact string `json:"contact,omitempty"`

	// Optional location
	Location string `json:"location,omitempty"`

	// Optional display name
	Name string `json:"name,omitempty"`

	// This is the exported private key from lotus wallet export
	PrivateKey string `json:"privateKey,omitempty"`
}

// Validate validates this wallet import request
func (m *WalletImportRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this wallet import request based on context it is used
func (m *WalletImportRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WalletImportRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WalletImportRequest) UnmarshalBinary(b []byte) error {
	var res WalletImportRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
