name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - xinaxu

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug here.
      render: text
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      value: |
        1. Run below commands
        ```
        singularity ...
        ```
        2. Go to '....'
        3. See error
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Singularity are you using?
      placeholder: Use 'singularity version' to get the version
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - MacOS
        - Windows
        - Other (specify in description)
    validations:
      required: true
  - type: dropdown
    id: database
    attributes:
      label: Database Backend
      description: What database backend are you using?
      options:
        - SQLite
        - MySQL
        - PostgreSQL
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
