// Code generated by go-swagger; DO NOT EDIT.

package preparation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// NewCreatePreparationParams creates a new CreatePreparationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreatePreparationParams() *CreatePreparationParams {
	return &CreatePreparationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreatePreparationParamsWithTimeout creates a new CreatePreparationParams object
// with the ability to set a timeout on a request.
func NewCreatePreparationParamsWithTimeout(timeout time.Duration) *CreatePreparationParams {
	return &CreatePreparationParams{
		timeout: timeout,
	}
}

// NewCreatePreparationParamsWithContext creates a new CreatePreparationParams object
// with the ability to set a context for a request.
func NewCreatePreparationParamsWithContext(ctx context.Context) *CreatePreparationParams {
	return &CreatePreparationParams{
		Context: ctx,
	}
}

// NewCreatePreparationParamsWithHTTPClient creates a new CreatePreparationParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreatePreparationParamsWithHTTPClient(client *http.Client) *CreatePreparationParams {
	return &CreatePreparationParams{
		HTTPClient: client,
	}
}

/*
CreatePreparationParams contains all the parameters to send to the API endpoint

	for the create preparation operation.

	Typically these are written to a http.Request.
*/
type CreatePreparationParams struct {

	/* Request.

	   Create Request
	*/
	Request *models.DataprepCreateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create preparation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePreparationParams) WithDefaults() *CreatePreparationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create preparation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePreparationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create preparation params
func (o *CreatePreparationParams) WithTimeout(timeout time.Duration) *CreatePreparationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create preparation params
func (o *CreatePreparationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create preparation params
func (o *CreatePreparationParams) WithContext(ctx context.Context) *CreatePreparationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create preparation params
func (o *CreatePreparationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create preparation params
func (o *CreatePreparationParams) WithHTTPClient(client *http.Client) *CreatePreparationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create preparation params
func (o *CreatePreparationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the create preparation params
func (o *CreatePreparationParams) WithRequest(request *models.DataprepCreateRequest) *CreatePreparationParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the create preparation params
func (o *CreatePreparationParams) SetRequest(request *models.DataprepCreateRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *CreatePreparationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
