// Code generated by go-swagger; DO NOT EDIT.

package deal_schedule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostScheduleIDResumeParams creates a new PostScheduleIDResumeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostScheduleIDResumeParams() *PostScheduleIDResumeParams {
	return &PostScheduleIDResumeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostScheduleIDResumeParamsWithTimeout creates a new PostScheduleIDResumeParams object
// with the ability to set a timeout on a request.
func NewPostScheduleIDResumeParamsWithTimeout(timeout time.Duration) *PostScheduleIDResumeParams {
	return &PostScheduleIDResumeParams{
		timeout: timeout,
	}
}

// NewPostScheduleIDResumeParamsWithContext creates a new PostScheduleIDResumeParams object
// with the ability to set a context for a request.
func NewPostScheduleIDResumeParamsWithContext(ctx context.Context) *PostScheduleIDResumeParams {
	return &PostScheduleIDResumeParams{
		Context: ctx,
	}
}

// NewPostScheduleIDResumeParamsWithHTTPClient creates a new PostScheduleIDResumeParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostScheduleIDResumeParamsWithHTTPClient(client *http.Client) *PostScheduleIDResumeParams {
	return &PostScheduleIDResumeParams{
		HTTPClient: client,
	}
}

/*
PostScheduleIDResumeParams contains all the parameters to send to the API endpoint

	for the post schedule ID resume operation.

	Typically these are written to a http.Request.
*/
type PostScheduleIDResumeParams struct {

	/* ID.

	   Schedule ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post schedule ID resume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostScheduleIDResumeParams) WithDefaults() *PostScheduleIDResumeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post schedule ID resume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostScheduleIDResumeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post schedule ID resume params
func (o *PostScheduleIDResumeParams) WithTimeout(timeout time.Duration) *PostScheduleIDResumeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post schedule ID resume params
func (o *PostScheduleIDResumeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post schedule ID resume params
func (o *PostScheduleIDResumeParams) WithContext(ctx context.Context) *PostScheduleIDResumeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post schedule ID resume params
func (o *PostScheduleIDResumeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post schedule ID resume params
func (o *PostScheduleIDResumeParams) WithHTTPClient(client *http.Client) *PostScheduleIDResumeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post schedule ID resume params
func (o *PostScheduleIDResumeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the post schedule ID resume params
func (o *PostScheduleIDResumeParams) WithID(id string) *PostScheduleIDResumeParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post schedule ID resume params
func (o *PostScheduleIDResumeParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostScheduleIDResumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
