// Code generated by go-swagger; DO NOT EDIT.

package deal_schedule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// RemoveScheduleReader is a Reader for the RemoveSchedule structure.
type RemoveScheduleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveScheduleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewRemoveScheduleNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRemoveScheduleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRemoveScheduleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /schedule/{id}] RemoveSchedule", response, response.Code())
	}
}

// NewRemoveScheduleNoContent creates a RemoveScheduleNoContent with default headers values
func NewRemoveScheduleNoContent() *RemoveScheduleNoContent {
	return &RemoveScheduleNoContent{}
}

/*
RemoveScheduleNoContent describes a response with status code 204, with default header values.

No Content
*/
type RemoveScheduleNoContent struct {
}

// IsSuccess returns true when this remove schedule no content response has a 2xx status code
func (o *RemoveScheduleNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this remove schedule no content response has a 3xx status code
func (o *RemoveScheduleNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove schedule no content response has a 4xx status code
func (o *RemoveScheduleNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this remove schedule no content response has a 5xx status code
func (o *RemoveScheduleNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this remove schedule no content response a status code equal to that given
func (o *RemoveScheduleNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the remove schedule no content response
func (o *RemoveScheduleNoContent) Code() int {
	return 204
}

func (o *RemoveScheduleNoContent) Error() string {
	return fmt.Sprintf("[DELETE /schedule/{id}][%d] removeScheduleNoContent", 204)
}

func (o *RemoveScheduleNoContent) String() string {
	return fmt.Sprintf("[DELETE /schedule/{id}][%d] removeScheduleNoContent", 204)
}

func (o *RemoveScheduleNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRemoveScheduleBadRequest creates a RemoveScheduleBadRequest with default headers values
func NewRemoveScheduleBadRequest() *RemoveScheduleBadRequest {
	return &RemoveScheduleBadRequest{}
}

/*
RemoveScheduleBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type RemoveScheduleBadRequest struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this remove schedule bad request response has a 2xx status code
func (o *RemoveScheduleBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this remove schedule bad request response has a 3xx status code
func (o *RemoveScheduleBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove schedule bad request response has a 4xx status code
func (o *RemoveScheduleBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this remove schedule bad request response has a 5xx status code
func (o *RemoveScheduleBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this remove schedule bad request response a status code equal to that given
func (o *RemoveScheduleBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the remove schedule bad request response
func (o *RemoveScheduleBadRequest) Code() int {
	return 400
}

func (o *RemoveScheduleBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /schedule/{id}][%d] removeScheduleBadRequest %s", 400, payload)
}

func (o *RemoveScheduleBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /schedule/{id}][%d] removeScheduleBadRequest %s", 400, payload)
}

func (o *RemoveScheduleBadRequest) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *RemoveScheduleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveScheduleInternalServerError creates a RemoveScheduleInternalServerError with default headers values
func NewRemoveScheduleInternalServerError() *RemoveScheduleInternalServerError {
	return &RemoveScheduleInternalServerError{}
}

/*
RemoveScheduleInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type RemoveScheduleInternalServerError struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this remove schedule internal server error response has a 2xx status code
func (o *RemoveScheduleInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this remove schedule internal server error response has a 3xx status code
func (o *RemoveScheduleInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove schedule internal server error response has a 4xx status code
func (o *RemoveScheduleInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this remove schedule internal server error response has a 5xx status code
func (o *RemoveScheduleInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this remove schedule internal server error response a status code equal to that given
func (o *RemoveScheduleInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the remove schedule internal server error response
func (o *RemoveScheduleInternalServerError) Code() int {
	return 500
}

func (o *RemoveScheduleInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /schedule/{id}][%d] removeScheduleInternalServerError %s", 500, payload)
}

func (o *RemoveScheduleInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /schedule/{id}][%d] removeScheduleInternalServerError %s", 500, payload)
}

func (o *RemoveScheduleInternalServerError) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *RemoveScheduleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
