// Code generated by go-swagger; DO NOT EDIT.

package deal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new deal API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for deal API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	ListDeals(params *ListDealsParams, opts ...ClientOption) (*ListDealsOK, error)

	SendManual(params *SendManualParams, opts ...ClientOption) (*SendManualOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
ListDeals lists all deals

List all deals
*/
func (a *Client) ListDeals(params *ListDealsParams, opts ...ClientOption) (*ListDealsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListDealsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ListDeals",
		Method:             "POST",
		PathPattern:        "/deal",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ListDealsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListDealsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ListDeals: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
SendManual sends a manual deal proposal

Send a manual deal proposal
*/
func (a *Client) SendManual(params *SendManualParams, opts ...ClientOption) (*SendManualOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSendManualParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "SendManual",
		Method:             "POST",
		PathPattern:        "/send_deal",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &SendManualReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SendManualOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for SendManual: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
