// Code generated by go-swagger; DO NOT EDIT.

package deal_template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// DeleteDealTemplateReader is a Reader for the DeleteDealTemplate structure.
type DeleteDealTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDealTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteDealTemplateNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteDealTemplateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteDealTemplateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteDealTemplateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /deal-template/{idOrName}] DeleteDealTemplate", response, response.Code())
	}
}

// NewDeleteDealTemplateNoContent creates a DeleteDealTemplateNoContent with default headers values
func NewDeleteDealTemplateNoContent() *DeleteDealTemplateNoContent {
	return &DeleteDealTemplateNoContent{}
}

/*
DeleteDealTemplateNoContent describes a response with status code 204, with default header values.

Deal template deleted successfully
*/
type DeleteDealTemplateNoContent struct {
}

// IsSuccess returns true when this delete deal template no content response has a 2xx status code
func (o *DeleteDealTemplateNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete deal template no content response has a 3xx status code
func (o *DeleteDealTemplateNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete deal template no content response has a 4xx status code
func (o *DeleteDealTemplateNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete deal template no content response has a 5xx status code
func (o *DeleteDealTemplateNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete deal template no content response a status code equal to that given
func (o *DeleteDealTemplateNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete deal template no content response
func (o *DeleteDealTemplateNoContent) Code() int {
	return 204
}

func (o *DeleteDealTemplateNoContent) Error() string {
	return fmt.Sprintf("[DELETE /deal-template/{idOrName}][%d] deleteDealTemplateNoContent", 204)
}

func (o *DeleteDealTemplateNoContent) String() string {
	return fmt.Sprintf("[DELETE /deal-template/{idOrName}][%d] deleteDealTemplateNoContent", 204)
}

func (o *DeleteDealTemplateNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDealTemplateBadRequest creates a DeleteDealTemplateBadRequest with default headers values
func NewDeleteDealTemplateBadRequest() *DeleteDealTemplateBadRequest {
	return &DeleteDealTemplateBadRequest{}
}

/*
DeleteDealTemplateBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DeleteDealTemplateBadRequest struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this delete deal template bad request response has a 2xx status code
func (o *DeleteDealTemplateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete deal template bad request response has a 3xx status code
func (o *DeleteDealTemplateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete deal template bad request response has a 4xx status code
func (o *DeleteDealTemplateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete deal template bad request response has a 5xx status code
func (o *DeleteDealTemplateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete deal template bad request response a status code equal to that given
func (o *DeleteDealTemplateBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete deal template bad request response
func (o *DeleteDealTemplateBadRequest) Code() int {
	return 400
}

func (o *DeleteDealTemplateBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /deal-template/{idOrName}][%d] deleteDealTemplateBadRequest %s", 400, payload)
}

func (o *DeleteDealTemplateBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /deal-template/{idOrName}][%d] deleteDealTemplateBadRequest %s", 400, payload)
}

func (o *DeleteDealTemplateBadRequest) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *DeleteDealTemplateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDealTemplateNotFound creates a DeleteDealTemplateNotFound with default headers values
func NewDeleteDealTemplateNotFound() *DeleteDealTemplateNotFound {
	return &DeleteDealTemplateNotFound{}
}

/*
DeleteDealTemplateNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteDealTemplateNotFound struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this delete deal template not found response has a 2xx status code
func (o *DeleteDealTemplateNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete deal template not found response has a 3xx status code
func (o *DeleteDealTemplateNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete deal template not found response has a 4xx status code
func (o *DeleteDealTemplateNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete deal template not found response has a 5xx status code
func (o *DeleteDealTemplateNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete deal template not found response a status code equal to that given
func (o *DeleteDealTemplateNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete deal template not found response
func (o *DeleteDealTemplateNotFound) Code() int {
	return 404
}

func (o *DeleteDealTemplateNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /deal-template/{idOrName}][%d] deleteDealTemplateNotFound %s", 404, payload)
}

func (o *DeleteDealTemplateNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /deal-template/{idOrName}][%d] deleteDealTemplateNotFound %s", 404, payload)
}

func (o *DeleteDealTemplateNotFound) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *DeleteDealTemplateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDealTemplateInternalServerError creates a DeleteDealTemplateInternalServerError with default headers values
func NewDeleteDealTemplateInternalServerError() *DeleteDealTemplateInternalServerError {
	return &DeleteDealTemplateInternalServerError{}
}

/*
DeleteDealTemplateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteDealTemplateInternalServerError struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this delete deal template internal server error response has a 2xx status code
func (o *DeleteDealTemplateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete deal template internal server error response has a 3xx status code
func (o *DeleteDealTemplateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete deal template internal server error response has a 4xx status code
func (o *DeleteDealTemplateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete deal template internal server error response has a 5xx status code
func (o *DeleteDealTemplateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete deal template internal server error response a status code equal to that given
func (o *DeleteDealTemplateInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete deal template internal server error response
func (o *DeleteDealTemplateInternalServerError) Code() int {
	return 500
}

func (o *DeleteDealTemplateInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /deal-template/{idOrName}][%d] deleteDealTemplateInternalServerError %s", 500, payload)
}

func (o *DeleteDealTemplateInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /deal-template/{idOrName}][%d] deleteDealTemplateInternalServerError %s", 500, payload)
}

func (o *DeleteDealTemplateInternalServerError) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *DeleteDealTemplateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
