// Code generated by go-swagger; DO NOT EDIT.

package deal_template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// ListDealTemplatesReader is a Reader for the ListDealTemplates structure.
type ListDealTemplatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListDealTemplatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListDealTemplatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewListDealTemplatesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /deal-template] ListDealTemplates", response, response.Code())
	}
}

// NewListDealTemplatesOK creates a ListDealTemplatesOK with default headers values
func NewListDealTemplatesOK() *ListDealTemplatesOK {
	return &ListDealTemplatesOK{}
}

/*
ListDealTemplatesOK describes a response with status code 200, with default header values.

OK
*/
type ListDealTemplatesOK struct {
	Payload []*models.ModelDealTemplate
}

// IsSuccess returns true when this list deal templates o k response has a 2xx status code
func (o *ListDealTemplatesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list deal templates o k response has a 3xx status code
func (o *ListDealTemplatesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list deal templates o k response has a 4xx status code
func (o *ListDealTemplatesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list deal templates o k response has a 5xx status code
func (o *ListDealTemplatesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list deal templates o k response a status code equal to that given
func (o *ListDealTemplatesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list deal templates o k response
func (o *ListDealTemplatesOK) Code() int {
	return 200
}

func (o *ListDealTemplatesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /deal-template][%d] listDealTemplatesOK %s", 200, payload)
}

func (o *ListDealTemplatesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /deal-template][%d] listDealTemplatesOK %s", 200, payload)
}

func (o *ListDealTemplatesOK) GetPayload() []*models.ModelDealTemplate {
	return o.Payload
}

func (o *ListDealTemplatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListDealTemplatesInternalServerError creates a ListDealTemplatesInternalServerError with default headers values
func NewListDealTemplatesInternalServerError() *ListDealTemplatesInternalServerError {
	return &ListDealTemplatesInternalServerError{}
}

/*
ListDealTemplatesInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type ListDealTemplatesInternalServerError struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this list deal templates internal server error response has a 2xx status code
func (o *ListDealTemplatesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list deal templates internal server error response has a 3xx status code
func (o *ListDealTemplatesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list deal templates internal server error response has a 4xx status code
func (o *ListDealTemplatesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list deal templates internal server error response has a 5xx status code
func (o *ListDealTemplatesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list deal templates internal server error response a status code equal to that given
func (o *ListDealTemplatesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the list deal templates internal server error response
func (o *ListDealTemplatesInternalServerError) Code() int {
	return 500
}

func (o *ListDealTemplatesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /deal-template][%d] listDealTemplatesInternalServerError %s", 500, payload)
}

func (o *ListDealTemplatesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /deal-template][%d] listDealTemplatesInternalServerError %s", 500, payload)
}

func (o *ListDealTemplatesInternalServerError) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *ListDealTemplatesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
