// Code generated by go-swagger; DO NOT EDIT.

package data_source

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// GetSourceIDPackjobsReader is a Reader for the GetSourceIDPackjobs structure.
type GetSourceIDPackjobsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSourceIDPackjobsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSourceIDPackjobsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetSourceIDPackjobsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetSourceIDPackjobsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /source/{id}/packjobs] GetSourceIDPackjobs", response, response.Code())
	}
}

// NewGetSourceIDPackjobsOK creates a GetSourceIDPackjobsOK with default headers values
func NewGetSourceIDPackjobsOK() *GetSourceIDPackjobsOK {
	return &GetSourceIDPackjobsOK{}
}

/*
GetSourceIDPackjobsOK describes a response with status code 200, with default header values.

OK
*/
type GetSourceIDPackjobsOK struct {
	Payload []*models.ModelPackJob
}

// IsSuccess returns true when this get source Id packjobs o k response has a 2xx status code
func (o *GetSourceIDPackjobsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get source Id packjobs o k response has a 3xx status code
func (o *GetSourceIDPackjobsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get source Id packjobs o k response has a 4xx status code
func (o *GetSourceIDPackjobsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get source Id packjobs o k response has a 5xx status code
func (o *GetSourceIDPackjobsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get source Id packjobs o k response a status code equal to that given
func (o *GetSourceIDPackjobsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get source Id packjobs o k response
func (o *GetSourceIDPackjobsOK) Code() int {
	return 200
}

func (o *GetSourceIDPackjobsOK) Error() string {
	return fmt.Sprintf("[GET /source/{id}/packjobs][%d] getSourceIdPackjobsOK  %+v", 200, o.Payload)
}

func (o *GetSourceIDPackjobsOK) String() string {
	return fmt.Sprintf("[GET /source/{id}/packjobs][%d] getSourceIdPackjobsOK  %+v", 200, o.Payload)
}

func (o *GetSourceIDPackjobsOK) GetPayload() []*models.ModelPackJob {
	return o.Payload
}

func (o *GetSourceIDPackjobsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSourceIDPackjobsBadRequest creates a GetSourceIDPackjobsBadRequest with default headers values
func NewGetSourceIDPackjobsBadRequest() *GetSourceIDPackjobsBadRequest {
	return &GetSourceIDPackjobsBadRequest{}
}

/*
GetSourceIDPackjobsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetSourceIDPackjobsBadRequest struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this get source Id packjobs bad request response has a 2xx status code
func (o *GetSourceIDPackjobsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get source Id packjobs bad request response has a 3xx status code
func (o *GetSourceIDPackjobsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get source Id packjobs bad request response has a 4xx status code
func (o *GetSourceIDPackjobsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get source Id packjobs bad request response has a 5xx status code
func (o *GetSourceIDPackjobsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get source Id packjobs bad request response a status code equal to that given
func (o *GetSourceIDPackjobsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get source Id packjobs bad request response
func (o *GetSourceIDPackjobsBadRequest) Code() int {
	return 400
}

func (o *GetSourceIDPackjobsBadRequest) Error() string {
	return fmt.Sprintf("[GET /source/{id}/packjobs][%d] getSourceIdPackjobsBadRequest  %+v", 400, o.Payload)
}

func (o *GetSourceIDPackjobsBadRequest) String() string {
	return fmt.Sprintf("[GET /source/{id}/packjobs][%d] getSourceIdPackjobsBadRequest  %+v", 400, o.Payload)
}

func (o *GetSourceIDPackjobsBadRequest) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *GetSourceIDPackjobsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSourceIDPackjobsInternalServerError creates a GetSourceIDPackjobsInternalServerError with default headers values
func NewGetSourceIDPackjobsInternalServerError() *GetSourceIDPackjobsInternalServerError {
	return &GetSourceIDPackjobsInternalServerError{}
}

/*
GetSourceIDPackjobsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetSourceIDPackjobsInternalServerError struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this get source Id packjobs internal server error response has a 2xx status code
func (o *GetSourceIDPackjobsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get source Id packjobs internal server error response has a 3xx status code
func (o *GetSourceIDPackjobsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get source Id packjobs internal server error response has a 4xx status code
func (o *GetSourceIDPackjobsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get source Id packjobs internal server error response has a 5xx status code
func (o *GetSourceIDPackjobsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get source Id packjobs internal server error response a status code equal to that given
func (o *GetSourceIDPackjobsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get source Id packjobs internal server error response
func (o *GetSourceIDPackjobsInternalServerError) Code() int {
	return 500
}

func (o *GetSourceIDPackjobsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /source/{id}/packjobs][%d] getSourceIdPackjobsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetSourceIDPackjobsInternalServerError) String() string {
	return fmt.Sprintf("[GET /source/{id}/packjobs][%d] getSourceIdPackjobsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetSourceIDPackjobsInternalServerError) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *GetSourceIDPackjobsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
