// Code generated by go-swagger; DO NOT EDIT.

package data_source

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// NewGetSourceIDPathParams creates a new GetSourceIDPathParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSourceIDPathParams() *GetSourceIDPathParams {
	return &GetSourceIDPathParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSourceIDPathParamsWithTimeout creates a new GetSourceIDPathParams object
// with the ability to set a timeout on a request.
func NewGetSourceIDPathParamsWithTimeout(timeout time.Duration) *GetSourceIDPathParams {
	return &GetSourceIDPathParams{
		timeout: timeout,
	}
}

// NewGetSourceIDPathParamsWithContext creates a new GetSourceIDPathParams object
// with the ability to set a context for a request.
func NewGetSourceIDPathParamsWithContext(ctx context.Context) *GetSourceIDPathParams {
	return &GetSourceIDPathParams{
		Context: ctx,
	}
}

// NewGetSourceIDPathParamsWithHTTPClient creates a new GetSourceIDPathParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSourceIDPathParamsWithHTTPClient(client *http.Client) *GetSourceIDPathParams {
	return &GetSourceIDPathParams{
		HTTPClient: client,
	}
}

/*
GetSourceIDPathParams contains all the parameters to send to the API endpoint

	for the get source ID path operation.

	Typically these are written to a http.Request.
*/
type GetSourceIDPathParams struct {

	/* ID.

	   Source ID
	*/
	ID string

	/* Request.

	   GetPathRequest
	*/
	Request *models.InspectGetPathRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get source ID path params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSourceIDPathParams) WithDefaults() *GetSourceIDPathParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get source ID path params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSourceIDPathParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get source ID path params
func (o *GetSourceIDPathParams) WithTimeout(timeout time.Duration) *GetSourceIDPathParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get source ID path params
func (o *GetSourceIDPathParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get source ID path params
func (o *GetSourceIDPathParams) WithContext(ctx context.Context) *GetSourceIDPathParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get source ID path params
func (o *GetSourceIDPathParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get source ID path params
func (o *GetSourceIDPathParams) WithHTTPClient(client *http.Client) *GetSourceIDPathParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get source ID path params
func (o *GetSourceIDPathParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get source ID path params
func (o *GetSourceIDPathParams) WithID(id string) *GetSourceIDPathParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get source ID path params
func (o *GetSourceIDPathParams) SetID(id string) {
	o.ID = id
}

// WithRequest adds the request to the get source ID path params
func (o *GetSourceIDPathParams) WithRequest(request *models.InspectGetPathRequest) *GetSourceIDPathParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the get source ID path params
func (o *GetSourceIDPathParams) SetRequest(request *models.InspectGetPathRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *GetSourceIDPathParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
