// Code generated by go-swagger; DO NOT EDIT.

package data_source

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// GetPackjobIDReader is a Reader for the GetPackjobID structure.
type GetPackjobIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPackjobIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPackjobIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetPackjobIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /packjob/{id}] GetPackjobID", response, response.Code())
	}
}

// NewGetPackjobIDOK creates a GetPackjobIDOK with default headers values
func NewGetPackjobIDOK() *GetPackjobIDOK {
	return &GetPackjobIDOK{}
}

/*
GetPackjobIDOK describes a response with status code 200, with default header values.

OK
*/
type GetPackjobIDOK struct {
	Payload *models.ModelPackJob
}

// IsSuccess returns true when this get packjob Id o k response has a 2xx status code
func (o *GetPackjobIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get packjob Id o k response has a 3xx status code
func (o *GetPackjobIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get packjob Id o k response has a 4xx status code
func (o *GetPackjobIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get packjob Id o k response has a 5xx status code
func (o *GetPackjobIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get packjob Id o k response a status code equal to that given
func (o *GetPackjobIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get packjob Id o k response
func (o *GetPackjobIDOK) Code() int {
	return 200
}

func (o *GetPackjobIDOK) Error() string {
	return fmt.Sprintf("[GET /packjob/{id}][%d] getPackjobIdOK  %+v", 200, o.Payload)
}

func (o *GetPackjobIDOK) String() string {
	return fmt.Sprintf("[GET /packjob/{id}][%d] getPackjobIdOK  %+v", 200, o.Payload)
}

func (o *GetPackjobIDOK) GetPayload() *models.ModelPackJob {
	return o.Payload
}

func (o *GetPackjobIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelPackJob)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPackjobIDInternalServerError creates a GetPackjobIDInternalServerError with default headers values
func NewGetPackjobIDInternalServerError() *GetPackjobIDInternalServerError {
	return &GetPackjobIDInternalServerError{}
}

/*
GetPackjobIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetPackjobIDInternalServerError struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this get packjob Id internal server error response has a 2xx status code
func (o *GetPackjobIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get packjob Id internal server error response has a 3xx status code
func (o *GetPackjobIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get packjob Id internal server error response has a 4xx status code
func (o *GetPackjobIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get packjob Id internal server error response has a 5xx status code
func (o *GetPackjobIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get packjob Id internal server error response a status code equal to that given
func (o *GetPackjobIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get packjob Id internal server error response
func (o *GetPackjobIDInternalServerError) Code() int {
	return 500
}

func (o *GetPackjobIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /packjob/{id}][%d] getPackjobIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetPackjobIDInternalServerError) String() string {
	return fmt.Sprintf("[GET /packjob/{id}][%d] getPackjobIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetPackjobIDInternalServerError) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *GetPackjobIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
