// Code generated by go-swagger; DO NOT EDIT.

package data_source

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// NewPostSourceIDCheckParams creates a new PostSourceIDCheckParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostSourceIDCheckParams() *PostSourceIDCheckParams {
	return &PostSourceIDCheckParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostSourceIDCheckParamsWithTimeout creates a new PostSourceIDCheckParams object
// with the ability to set a timeout on a request.
func NewPostSourceIDCheckParamsWithTimeout(timeout time.Duration) *PostSourceIDCheckParams {
	return &PostSourceIDCheckParams{
		timeout: timeout,
	}
}

// NewPostSourceIDCheckParamsWithContext creates a new PostSourceIDCheckParams object
// with the ability to set a context for a request.
func NewPostSourceIDCheckParamsWithContext(ctx context.Context) *PostSourceIDCheckParams {
	return &PostSourceIDCheckParams{
		Context: ctx,
	}
}

// NewPostSourceIDCheckParamsWithHTTPClient creates a new PostSourceIDCheckParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostSourceIDCheckParamsWithHTTPClient(client *http.Client) *PostSourceIDCheckParams {
	return &PostSourceIDCheckParams{
		HTTPClient: client,
	}
}

/*
PostSourceIDCheckParams contains all the parameters to send to the API endpoint

	for the post source ID check operation.

	Typically these are written to a http.Request.
*/
type PostSourceIDCheckParams struct {

	/* ID.

	   Source ID
	*/
	ID string

	/* Request.

	   Request body
	*/
	Request *models.DatasourceCheckSourceRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post source ID check params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostSourceIDCheckParams) WithDefaults() *PostSourceIDCheckParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post source ID check params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostSourceIDCheckParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post source ID check params
func (o *PostSourceIDCheckParams) WithTimeout(timeout time.Duration) *PostSourceIDCheckParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post source ID check params
func (o *PostSourceIDCheckParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post source ID check params
func (o *PostSourceIDCheckParams) WithContext(ctx context.Context) *PostSourceIDCheckParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post source ID check params
func (o *PostSourceIDCheckParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post source ID check params
func (o *PostSourceIDCheckParams) WithHTTPClient(client *http.Client) *PostSourceIDCheckParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post source ID check params
func (o *PostSourceIDCheckParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the post source ID check params
func (o *PostSourceIDCheckParams) WithID(id string) *PostSourceIDCheckParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post source ID check params
func (o *PostSourceIDCheckParams) SetID(id string) {
	o.ID = id
}

// WithRequest adds the request to the post source ID check params
func (o *PostSourceIDCheckParams) WithRequest(request *models.DatasourceCheckSourceRequest) *PostSourceIDCheckParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post source ID check params
func (o *PostSourceIDCheckParams) SetRequest(request *models.DatasourceCheckSourceRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostSourceIDCheckParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
