// Code generated by go-swagger; DO NOT EDIT.

package piece

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// DeletePieceReader is a Reader for the DeletePiece structure.
type DeletePieceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePieceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewDeletePieceNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeletePieceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeletePieceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeletePieceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /preparation/{id}/piece/{piece_cid}] DeletePiece", response, response.Code())
	}
}

// NewDeletePieceNoContent creates a DeletePieceNoContent with default headers values
func NewDeletePieceNoContent() *DeletePieceNoContent {
	return &DeletePieceNoContent{}
}

/*
DeletePieceNoContent describes a response with status code 204, with default header values.

No Content
*/
type DeletePieceNoContent struct {
}

// IsSuccess returns true when this delete piece no content response has a 2xx status code
func (o *DeletePieceNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete piece no content response has a 3xx status code
func (o *DeletePieceNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete piece no content response has a 4xx status code
func (o *DeletePieceNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete piece no content response has a 5xx status code
func (o *DeletePieceNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete piece no content response a status code equal to that given
func (o *DeletePieceNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete piece no content response
func (o *DeletePieceNoContent) Code() int {
	return 204
}

func (o *DeletePieceNoContent) Error() string {
	return fmt.Sprintf("[DELETE /preparation/{id}/piece/{piece_cid}][%d] deletePieceNoContent", 204)
}

func (o *DeletePieceNoContent) String() string {
	return fmt.Sprintf("[DELETE /preparation/{id}/piece/{piece_cid}][%d] deletePieceNoContent", 204)
}

func (o *DeletePieceNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePieceBadRequest creates a DeletePieceBadRequest with default headers values
func NewDeletePieceBadRequest() *DeletePieceBadRequest {
	return &DeletePieceBadRequest{}
}

/*
DeletePieceBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DeletePieceBadRequest struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this delete piece bad request response has a 2xx status code
func (o *DeletePieceBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete piece bad request response has a 3xx status code
func (o *DeletePieceBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete piece bad request response has a 4xx status code
func (o *DeletePieceBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete piece bad request response has a 5xx status code
func (o *DeletePieceBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete piece bad request response a status code equal to that given
func (o *DeletePieceBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete piece bad request response
func (o *DeletePieceBadRequest) Code() int {
	return 400
}

func (o *DeletePieceBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /preparation/{id}/piece/{piece_cid}][%d] deletePieceBadRequest %s", 400, payload)
}

func (o *DeletePieceBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /preparation/{id}/piece/{piece_cid}][%d] deletePieceBadRequest %s", 400, payload)
}

func (o *DeletePieceBadRequest) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *DeletePieceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeletePieceNotFound creates a DeletePieceNotFound with default headers values
func NewDeletePieceNotFound() *DeletePieceNotFound {
	return &DeletePieceNotFound{}
}

/*
DeletePieceNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeletePieceNotFound struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this delete piece not found response has a 2xx status code
func (o *DeletePieceNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete piece not found response has a 3xx status code
func (o *DeletePieceNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete piece not found response has a 4xx status code
func (o *DeletePieceNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete piece not found response has a 5xx status code
func (o *DeletePieceNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete piece not found response a status code equal to that given
func (o *DeletePieceNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete piece not found response
func (o *DeletePieceNotFound) Code() int {
	return 404
}

func (o *DeletePieceNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /preparation/{id}/piece/{piece_cid}][%d] deletePieceNotFound %s", 404, payload)
}

func (o *DeletePieceNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /preparation/{id}/piece/{piece_cid}][%d] deletePieceNotFound %s", 404, payload)
}

func (o *DeletePieceNotFound) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *DeletePieceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeletePieceInternalServerError creates a DeletePieceInternalServerError with default headers values
func NewDeletePieceInternalServerError() *DeletePieceInternalServerError {
	return &DeletePieceInternalServerError{}
}

/*
DeletePieceInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeletePieceInternalServerError struct {
	Payload *models.APIHTTPError
}

// IsSuccess returns true when this delete piece internal server error response has a 2xx status code
func (o *DeletePieceInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete piece internal server error response has a 3xx status code
func (o *DeletePieceInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete piece internal server error response has a 4xx status code
func (o *DeletePieceInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete piece internal server error response has a 5xx status code
func (o *DeletePieceInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete piece internal server error response a status code equal to that given
func (o *DeletePieceInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete piece internal server error response
func (o *DeletePieceInternalServerError) Code() int {
	return 500
}

func (o *DeletePieceInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /preparation/{id}/piece/{piece_cid}][%d] deletePieceInternalServerError %s", 500, payload)
}

func (o *DeletePieceInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /preparation/{id}/piece/{piece_cid}][%d] deletePieceInternalServerError %s", 500, payload)
}

func (o *DeletePieceInternalServerError) GetPayload() *models.APIHTTPError {
	return o.Payload
}

func (o *DeletePieceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
