// Code generated by go-swagger; DO NOT EDIT.

package preparation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// NewRenamePreparationParams creates a new RenamePreparationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRenamePreparationParams() *RenamePreparationParams {
	return &RenamePreparationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRenamePreparationParamsWithTimeout creates a new RenamePreparationParams object
// with the ability to set a timeout on a request.
func NewRenamePreparationParamsWithTimeout(timeout time.Duration) *RenamePreparationParams {
	return &RenamePreparationParams{
		timeout: timeout,
	}
}

// NewRenamePreparationParamsWithContext creates a new RenamePreparationParams object
// with the ability to set a context for a request.
func NewRenamePreparationParamsWithContext(ctx context.Context) *RenamePreparationParams {
	return &RenamePreparationParams{
		Context: ctx,
	}
}

// NewRenamePreparationParamsWithHTTPClient creates a new RenamePreparationParams object
// with the ability to set a custom HTTPClient for a request.
func NewRenamePreparationParamsWithHTTPClient(client *http.Client) *RenamePreparationParams {
	return &RenamePreparationParams{
		HTTPClient: client,
	}
}

/*
RenamePreparationParams contains all the parameters to send to the API endpoint

	for the rename preparation operation.

	Typically these are written to a http.Request.
*/
type RenamePreparationParams struct {

	/* Name.

	   Preparation ID or name
	*/
	Name string

	/* Request.

	   New preparation name
	*/
	Request *models.DataprepRenameRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the rename preparation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RenamePreparationParams) WithDefaults() *RenamePreparationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the rename preparation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RenamePreparationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the rename preparation params
func (o *RenamePreparationParams) WithTimeout(timeout time.Duration) *RenamePreparationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rename preparation params
func (o *RenamePreparationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rename preparation params
func (o *RenamePreparationParams) WithContext(ctx context.Context) *RenamePreparationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rename preparation params
func (o *RenamePreparationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rename preparation params
func (o *RenamePreparationParams) WithHTTPClient(client *http.Client) *RenamePreparationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rename preparation params
func (o *RenamePreparationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the rename preparation params
func (o *RenamePreparationParams) WithName(name string) *RenamePreparationParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the rename preparation params
func (o *RenamePreparationParams) SetName(name string) {
	o.Name = name
}

// WithRequest adds the request to the rename preparation params
func (o *RenamePreparationParams) WithRequest(request *models.DataprepRenameRequest) *RenamePreparationParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the rename preparation params
func (o *RenamePreparationParams) SetRequest(request *models.DataprepRenameRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *RenamePreparationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
