// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// NewPostPreparationIDSourceNameFileParams creates a new PostPreparationIDSourceNameFileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostPreparationIDSourceNameFileParams() *PostPreparationIDSourceNameFileParams {
	return &PostPreparationIDSourceNameFileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostPreparationIDSourceNameFileParamsWithTimeout creates a new PostPreparationIDSourceNameFileParams object
// with the ability to set a timeout on a request.
func NewPostPreparationIDSourceNameFileParamsWithTimeout(timeout time.Duration) *PostPreparationIDSourceNameFileParams {
	return &PostPreparationIDSourceNameFileParams{
		timeout: timeout,
	}
}

// NewPostPreparationIDSourceNameFileParamsWithContext creates a new PostPreparationIDSourceNameFileParams object
// with the ability to set a context for a request.
func NewPostPreparationIDSourceNameFileParamsWithContext(ctx context.Context) *PostPreparationIDSourceNameFileParams {
	return &PostPreparationIDSourceNameFileParams{
		Context: ctx,
	}
}

// NewPostPreparationIDSourceNameFileParamsWithHTTPClient creates a new PostPreparationIDSourceNameFileParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostPreparationIDSourceNameFileParamsWithHTTPClient(client *http.Client) *PostPreparationIDSourceNameFileParams {
	return &PostPreparationIDSourceNameFileParams{
		HTTPClient: client,
	}
}

/*
PostPreparationIDSourceNameFileParams contains all the parameters to send to the API endpoint

	for the post preparation ID source name file operation.

	Typically these are written to a http.Request.
*/
type PostPreparationIDSourceNameFileParams struct {

	/* File.

	   File Info
	*/
	File *models.FileInfo

	/* ID.

	   Preparation ID or name
	*/
	ID string

	/* Name.

	   Source storage ID or name
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post preparation ID source name file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostPreparationIDSourceNameFileParams) WithDefaults() *PostPreparationIDSourceNameFileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post preparation ID source name file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostPreparationIDSourceNameFileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post preparation ID source name file params
func (o *PostPreparationIDSourceNameFileParams) WithTimeout(timeout time.Duration) *PostPreparationIDSourceNameFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post preparation ID source name file params
func (o *PostPreparationIDSourceNameFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post preparation ID source name file params
func (o *PostPreparationIDSourceNameFileParams) WithContext(ctx context.Context) *PostPreparationIDSourceNameFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post preparation ID source name file params
func (o *PostPreparationIDSourceNameFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post preparation ID source name file params
func (o *PostPreparationIDSourceNameFileParams) WithHTTPClient(client *http.Client) *PostPreparationIDSourceNameFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post preparation ID source name file params
func (o *PostPreparationIDSourceNameFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFile adds the file to the post preparation ID source name file params
func (o *PostPreparationIDSourceNameFileParams) WithFile(file *models.FileInfo) *PostPreparationIDSourceNameFileParams {
	o.SetFile(file)
	return o
}

// SetFile adds the file to the post preparation ID source name file params
func (o *PostPreparationIDSourceNameFileParams) SetFile(file *models.FileInfo) {
	o.File = file
}

// WithID adds the id to the post preparation ID source name file params
func (o *PostPreparationIDSourceNameFileParams) WithID(id string) *PostPreparationIDSourceNameFileParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post preparation ID source name file params
func (o *PostPreparationIDSourceNameFileParams) SetID(id string) {
	o.ID = id
}

// WithName adds the name to the post preparation ID source name file params
func (o *PostPreparationIDSourceNameFileParams) WithName(name string) *PostPreparationIDSourceNameFileParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the post preparation ID source name file params
func (o *PostPreparationIDSourceNameFileParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PostPreparationIDSourceNameFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.File != nil {
		if err := r.SetBodyParam(o.File); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
