// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPauseDagGenParams creates a new PauseDagGenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPauseDagGenParams() *PauseDagGenParams {
	return &PauseDagGenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPauseDagGenParamsWithTimeout creates a new PauseDagGenParams object
// with the ability to set a timeout on a request.
func NewPauseDagGenParamsWithTimeout(timeout time.Duration) *PauseDagGenParams {
	return &PauseDagGenParams{
		timeout: timeout,
	}
}

// NewPauseDagGenParamsWithContext creates a new PauseDagGenParams object
// with the ability to set a context for a request.
func NewPauseDagGenParamsWithContext(ctx context.Context) *PauseDagGenParams {
	return &PauseDagGenParams{
		Context: ctx,
	}
}

// NewPauseDagGenParamsWithHTTPClient creates a new PauseDagGenParams object
// with the ability to set a custom HTTPClient for a request.
func NewPauseDagGenParamsWithHTTPClient(client *http.Client) *PauseDagGenParams {
	return &PauseDagGenParams{
		HTTPClient: client,
	}
}

/*
PauseDagGenParams contains all the parameters to send to the API endpoint

	for the pause dag gen operation.

	Typically these are written to a http.Request.
*/
type PauseDagGenParams struct {

	/* ID.

	   Preparation ID or name
	*/
	ID string

	/* Name.

	   Storage ID or name
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pause dag gen params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PauseDagGenParams) WithDefaults() *PauseDagGenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pause dag gen params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PauseDagGenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pause dag gen params
func (o *PauseDagGenParams) WithTimeout(timeout time.Duration) *PauseDagGenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pause dag gen params
func (o *PauseDagGenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pause dag gen params
func (o *PauseDagGenParams) WithContext(ctx context.Context) *PauseDagGenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pause dag gen params
func (o *PauseDagGenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pause dag gen params
func (o *PauseDagGenParams) WithHTTPClient(client *http.Client) *PauseDagGenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pause dag gen params
func (o *PauseDagGenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the pause dag gen params
func (o *PauseDagGenParams) WithID(id string) *PauseDagGenParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the pause dag gen params
func (o *PauseDagGenParams) SetID(id string) {
	o.ID = id
}

// WithName adds the name to the pause dag gen params
func (o *PauseDagGenParams) WithName(name string) *PauseDagGenParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the pause dag gen params
func (o *PauseDagGenParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PauseDagGenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
