// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/data-preservation-programs/singularity/client/swagger/models"
)

// PostJobIDPackReader is a Reader for the PostJobIDPack structure.
type PostJobIDPackReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostJobIDPackReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostJobIDPackOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostJobIDPackBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostJobIDPackInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /job/{id}/pack] PostJobIDPack", response, response.Code())
	}
}

// NewPostJobIDPackOK creates a PostJobIDPackOK with default headers values
func NewPostJobIDPackOK() *PostJobIDPackOK {
	return &PostJobIDPackOK{}
}

/*
PostJobIDPackOK describes a response with status code 200, with default header values.

OK
*/
type PostJobIDPackOK struct {
	Payload *models.ModelCar
}

// IsSuccess returns true when this post job Id pack o k response has a 2xx status code
func (o *PostJobIDPackOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post job Id pack o k response has a 3xx status code
func (o *PostJobIDPackOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post job Id pack o k response has a 4xx status code
func (o *PostJobIDPackOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post job Id pack o k response has a 5xx status code
func (o *PostJobIDPackOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post job Id pack o k response a status code equal to that given
func (o *PostJobIDPackOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post job Id pack o k response
func (o *PostJobIDPackOK) Code() int {
	return 200
}

func (o *PostJobIDPackOK) Error() string {
	return fmt.Sprintf("[POST /job/{id}/pack][%d] postJobIdPackOK  %+v", 200, o.Payload)
}

func (o *PostJobIDPackOK) String() string {
	return fmt.Sprintf("[POST /job/{id}/pack][%d] postJobIdPackOK  %+v", 200, o.Payload)
}

func (o *PostJobIDPackOK) GetPayload() *models.ModelCar {
	return o.Payload
}

func (o *PostJobIDPackOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelCar)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostJobIDPackBadRequest creates a PostJobIDPackBadRequest with default headers values
func NewPostJobIDPackBadRequest() *PostJobIDPackBadRequest {
	return &PostJobIDPackBadRequest{}
}

/*
PostJobIDPackBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostJobIDPackBadRequest struct {
	Payload string
}

// IsSuccess returns true when this post job Id pack bad request response has a 2xx status code
func (o *PostJobIDPackBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post job Id pack bad request response has a 3xx status code
func (o *PostJobIDPackBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post job Id pack bad request response has a 4xx status code
func (o *PostJobIDPackBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post job Id pack bad request response has a 5xx status code
func (o *PostJobIDPackBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post job Id pack bad request response a status code equal to that given
func (o *PostJobIDPackBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post job Id pack bad request response
func (o *PostJobIDPackBadRequest) Code() int {
	return 400
}

func (o *PostJobIDPackBadRequest) Error() string {
	return fmt.Sprintf("[POST /job/{id}/pack][%d] postJobIdPackBadRequest  %+v", 400, o.Payload)
}

func (o *PostJobIDPackBadRequest) String() string {
	return fmt.Sprintf("[POST /job/{id}/pack][%d] postJobIdPackBadRequest  %+v", 400, o.Payload)
}

func (o *PostJobIDPackBadRequest) GetPayload() string {
	return o.Payload
}

func (o *PostJobIDPackBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostJobIDPackInternalServerError creates a PostJobIDPackInternalServerError with default headers values
func NewPostJobIDPackInternalServerError() *PostJobIDPackInternalServerError {
	return &PostJobIDPackInternalServerError{}
}

/*
PostJobIDPackInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostJobIDPackInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this post job Id pack internal server error response has a 2xx status code
func (o *PostJobIDPackInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post job Id pack internal server error response has a 3xx status code
func (o *PostJobIDPackInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post job Id pack internal server error response has a 4xx status code
func (o *PostJobIDPackInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post job Id pack internal server error response has a 5xx status code
func (o *PostJobIDPackInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post job Id pack internal server error response a status code equal to that given
func (o *PostJobIDPackInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post job Id pack internal server error response
func (o *PostJobIDPackInternalServerError) Code() int {
	return 500
}

func (o *PostJobIDPackInternalServerError) Error() string {
	return fmt.Sprintf("[POST /job/{id}/pack][%d] postJobIdPackInternalServerError  %+v", 500, o.Payload)
}

func (o *PostJobIDPackInternalServerError) String() string {
	return fmt.Sprintf("[POST /job/{id}/pack][%d] postJobIdPackInternalServerError  %+v", 500, o.Payload)
}

func (o *PostJobIDPackInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *PostJobIDPackInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
