name: Setup Cache
description: Setup Cache
runs:
  using: "composite"
  steps:
    - name: Setup Golang caches
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ matrix.os }}-golang-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ matrix.os }}-golang-${{ matrix.go }}-

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version || 'stable' }}

    - name: Lint
      uses: golangci/golangci-lint-action@v7
      with:
        version: v2.1.2
        args: --timeout=10m
