name: Documentation Generation

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docgen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Initialize database for doc generation
        run: |
          cd singularity
          ./singularity admin init
      - name: Generate documentation
        run: |
          cd singularity
          sh docgen.sh
