name: Integration Tests

on:
  pull_request:
    paths:
      # Run when integration test files are modified
      - 'cmd/auto_prep_deals_integration_test.go'
      - 'cmd/*_integration_test.go'
      
      # Run when related source files are modified
      - 'cmd/deal/**'
      - 'cmd/dataset/**'
      - 'cmd/storage/**'
      - 'cmd/wallet/**'
      - 'cmd/run/**'
      - 'cmd/job/**'
      
      # Run when core functionality changes
      - 'handler/deal/**'
      - 'handler/dataset/**'
      - 'handler/storage/**'
      - 'handler/wallet/**'
      - 'handler/job/**'
      
      # Run when worker and scheduler code changes
      - 'worker/**'
      - 'scheduler/**'
      
      # Run when models change
      - 'model/**'
      
      # Run when database migrations change
      - 'migrate/**'
      
      # Run when workflow itself changes
      - '.github/workflows/integration-test.yml'
      
  push:
    branches: ["main"]
    paths:
      # Same paths as pull_request
      - 'cmd/auto_prep_deals_integration_test.go'
      - 'cmd/*_integration_test.go'
      - 'cmd/deal/**'
      - 'cmd/dataset/**'
      - 'cmd/storage/**'
      - 'cmd/wallet/**'
      - 'cmd/run/**'
      - 'cmd/job/**'
      - 'handler/deal/**'
      - 'handler/dataset/**'
      - 'handler/storage/**'
      - 'handler/wallet/**'
      - 'handler/job/**'
      - 'worker/**'
      - 'scheduler/**'
      - 'model/**'
      - 'migrate/**'
      - '.github/workflows/integration-test.yml'
      
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          
      - name: Install dependencies
        run: go mod download
        
      - name: Run integration tests
        run: |
          # Run only integration tests with verbose output
          go test -v -timeout 20m -run "Integration" ./cmd/...
        env:
          # Set any required environment variables for integration tests
          SINGULARITY_TEST_INTEGRATION: "true"